export const data = [
    {
        id: 1,
        name: 'хороший старт',
        data: '28.01.2024',
        cover1: 1,
        cover2: 2,
        shorts: [
            {
                id: 101,
                name: 'Не кормите голубей',
                originalName: 'Do Not Feed the Pigeons',
                yearProduction: 2021,
                country: 'Великобритания',
                director: 'Антонин Никласс',
                scenario: 'Vladimir Krasilnikov',
                producer: 'Джорди Морера',
                operator: 'Rui Jiang Ong, Taylor Shulin',
                composer: 'Фабио Амурри',
                artist: 'Ив Финни, Китти Финни',
                installation: 'Lorene Dewett',
                worldPremiere: '7 сентября 2021',
                age:'',
                time: '9 мин', 
                description: 'На автовокзале около 2 часов ночи в ожидании автобуса коротает время стайка одиноких усталых путешественников. Каким-то образом местным голубям удаётся, пусть и на мгновение, создать между людьми волшебную связь.',
                poster: '/posters/1/101.webp',
                film: 'https://vk.com/video-31920686_456240528',
                kinopoisk: 'https://www.kinopoisk.ru/film/4884386/',
            },
            {
                id: 102,
                name: 'Стеклоочиститель',
                originalName: 'The Windshield Wiper',
                yearProduction: 2021,
                country: 'Испания, США',
                director: 'Альберто Мьельго',
                scenario: 'Альберто Мьельго',
                producer: 'Мануэль Р. Кристобаль, Jordan Harkins, Альберто Мьельго, ...',
                operator: '',
                composer: '',
                artist: '',
                installation: 'Альберто Мьельго',
                worldPremiere: '13 июля 2021',
                age:'18+',
                time: '15 мин', 
                description: 'Сидя в кафе и непрерывно куря, мужчина задается вопросом, что такое любовь.',
                poster: '/posters/1/102.webp',
                film: 'https://www.kinopoisk.ru/film/4470495/',
                kinopoisk: 'https://www.kinopoisk.ru/film/4470495/'
            },
            {
                id: 103,
                name: 'Летающий моряк',
                originalName: 'The Flying Sailor',
                yearProduction: 2022,
                country: 'Канада',
                director: 'Аманда Форбис, Венди Тилби',
                scenario: 'Аманда Форбис, Венди Тилби',
                producer: 'Дэвид Кристенсен',
                operator: '',
                composer: 'Луиджи Аллемано',
                artist: '',
                installation: '',
                worldPremiere: '13 июня 2022',
                age:'',
                time: '8 мин', 
                description: 'Два корабля сталкиваются в гавани, отправляя проходящего мимо моряка ввысь, и он созерцает чудо и хрупкость существования.',
                poster: '/posters/1/103.webp',
                film: 'https://www.kinopoisk.ru/film/5136457/',
                kinopoisk: 'https://www.kinopoisk.ru/film/5136457/'
            },
            {
                id: 104,
                name: 'Продавцы льда',
                originalName: 'Ice Merchants',
                yearProduction: 2022,
                country: 'Португалия, Великобритания, Франция',
                director: 'Жоау Гонсалес',
                scenario: 'Жоау Гонсалес',
                producer: 'Бруно Каэтано, Michael Proenca',
                operator: 'Жоау Гонсалес',
                composer: 'Жоау Гонсалес',
                artist: 'Жоау Гонсалес',
                installation: 'Жоау Гонсалес',
                worldPremiere: '24 мая 2022',
                age:'',
                time: '14 мин', 
                description: 'Отец и сын живут на вершине скалы. Каждый день они спускаются вниз на парашютах, чтобы продавать лёд в деревушке, расположенной под их скалой.',
                poster: '/posters/1/104.webp',
                film: 'https://www.kinopoisk.ru/film/5234141/',
                kinopoisk: 'https://www.kinopoisk.ru/film/5234141/'
            },
            {
                id: 105,
                name: 'Мальчик, Крот, Лис и Конь',
                originalName: 'The Boy, the Mole, the Fox and the Horse',
                yearProduction: 2022,
                country: 'Великобритания, США',
                director: 'Питер Бэйнтон, Чарли Маккизи',
                scenario: 'Джон Крокер, Чарли Маккизи',
                producer: 'Джей Джей Абрамс, Мэттью Фройд, Ханна Мингелла, ...',
                operator: '',
                composer: 'Изобель Уоллер-Бридж',
                artist: 'Майк Маккэйн',
                installation: 'Дэниэл Бадин',
                worldPremiere: '23 сентября 2022',
                age:'',
                time: '32 мин', 
                description: 'Гуляя в зимнем лесу, мальчик встречает крота, лиса и коня, с которыми ведёт разговоры о доброте, пирогах, любви к себе и доме. Несмотря на многочисленные различия, компании удаётся найти общий язык и хорошо провести время.',
                poster: '/posters/1/105.webp',
                film: 'https://www.kinopoisk.ru/film/5138530/',
                kinopoisk: 'https://www.kinopoisk.ru/film/5138530/'
            }
        ]
    },
    {
        id: 2,
        name: 'находки',
        data: '18.02.2024',
        cover1: 1,
        cover2: 2,
        shorts: [
            {
                id: 201,
                name: 'Падальщики',
                originalName: 'Scavengers',
                yearProduction: 2016,
                country: 'США',
                director: 'Джо Беннетт, Чарльз Хюттнер',
                scenario: 'Джо Беннетт, Чарльз Хюттнер',
                producer: 'Мэтт Харриган, Дэйв Ньюберг',
                operator: '',
                composer: 'Дидье Лепла, Джо Вон',
                artist: '',
                installation: '',
                worldPremiere: '24 декабря 2016',
                age:'',
                time: '8 мин', 
                description: 'Миссия «Веста-1» была организована для основания поселения на планете Малая Веста. Вскоре после приземления корабля связь с экипажем пропадает.',
                poster: '/posters/2/201.webp',
                film: 'https://vk.com/video-31920686_456240528',
                kinopoisk: 'https://vk.com/video217012430_456239353',
            },
            {
                id: 202,
                name: 'Find True Love',
                originalName: 'Find True Love',
                yearProduction: 2016,
                country: 'США',
                director: 'Ларс фон Триер',
                scenario: 'Ларс фон Триер',
                producer: '-',
                operator: 'Ларс фон Триер',
                composer: '-',
                artist: '',
                installation: 'Ларс фон Триер',
                worldPremiere: '',
                age:'',
                time: '2 мин', 
                description: 'История-песенка о Суперколбаске, который выручает зайца из плена бандитов.',
                poster: '/posters/2/202.webp',
                film: 'https://vk.com/video-62812096_456239024',
                kinopoisk: 'https://www.kinopoisk.ru/film/5101424/',
            },
            {
                id: 203,
                name: 'Pizza Movie',
                originalName: 'Pizza Movie',
                yearProduction: 2016,
                country: 'США',
                director: 'Виктория Винсент',
                scenario: 'Виктория Винсент',
                producer: '-',
                operator: '',
                composer: '-',
                artist: '',
                installation: 'Виктория Винсент',
                worldPremiere: '12 октября 2016',
                age:'',
                time: '1 мин', 
                description: '',
                poster: '/posters/2/203.webp',
                film: 'https://vk.com/video-62812096_456239048',
                kinopoisk: 'https://www.kinopoisk.ru/film/5130677/',
            },
            {
                id: 204,
                name: 'Путешествие в сплющенную страну',
                originalName: 'Turen til Squashland',
                yearProduction: 1967,
                country: 'Дания',
                director: 'Ларс фон Триер',
                scenario: 'Ларс фон Триер',
                producer: '-',
                operator: '',
                composer: '-',
                artist: '',
                installation: 'Ларс фон Триер',
                worldPremiere: '12 октября 2016',
                age:'',
                time: '1 мин', 
                description: '',
                poster: '/posters/2/204.webp',
                film: 'https://www.youtube.com/watch?v=ZxZrvn9s8x8',
                kinopoisk: 'https://www.kinopoisk.ru/film/309460/',
            },
            {
                id: 205,
                name: 'Шестеро заболевают',
                originalName: 'Six Men Getting Sick',
                yearProduction: 1967,
                country: 'США',
                director: 'Дэвид Линч',
                scenario: '-',
                producer: 'Дэвид Линч',
                operator: '',
                composer: '-',
                artist: '',
                installation: 'Дэвид Линч',
                worldPremiere: '3 февраля 2007',
                age:'',
                time: '4 мин', 
                description: '',
                poster: '/posters/2/205.webp',
                film: 'https://vk.com/video328194378_456239727',
                kinopoisk: 'https://www.kinopoisk.ru/film/15811/',
            },
            {
                id: 206,
                name: 'Свидетель',
                originalName: 'The Witness',
                yearProduction: 2019,
                country: 'США',
                director: 'Альберто Мьельго',
                scenario: '?',
                producer: '?',
                operator: '?',
                composer: '?',
                artist: '?',
                installation: '?',
                worldPremiere: '15 марта 2019',
                age:'18+',
                time: '11 мин', 
                description: '',
                poster: '/posters/2/206.webp',
                film: 'https://vk.com/video-176294899_456240758',
                kinopoisk: 'https://www.kinopoisk.ru/series/1228254/',
            },
            {
                id: 206,
                name: 'Свидетель',
                originalName: 'The Witness',
                yearProduction: 2019,
                country: 'США',
                director: 'Альберто Мьельго',
                scenario: '?',
                producer: '?',
                operator: '?',
                composer: '?',
                artist: '?',
                installation: '?',
                worldPremiere: '15 марта 2019',
                age:'18+',
                time: '11 мин', 
                description: '',
                poster: '/posters/2/206.webp',
                film: 'https://vk.com/video-176294899_456240758',
                kinopoisk: 'https://www.kinopoisk.ru/series/1228254/',
            },
            {
                id: 207,
                name: 'Гений места',
                originalName: 'Genius Loci',
                yearProduction: 2020,
                country: 'Франция',
                director: 'Адриен Мериго',
                scenario: 'Адриен Мериго, Николя Плескоф',
                producer: 'Амори Овиз, Реджинальд де Гийбон, Энгерран Детервиль, ...',
                operator: '',
                composer: 'Тео Мериго, Ле Квон Нинх',
                artist: '',
                installation: '',
                worldPremiere: '19 января 2020',
                age:'',
                time: '16 мин', 
                description: 'Однажды ночью Рейн, одинокая девушка, видит среди городского хаоса подвижное единство, которое кажется живым, вроде какого-то проводника.',
                poster: '/posters/2/207.webp',
                film: 'https://vk.com/video140140535_456239567',
                kinopoisk: 'https://www.kinopoisk.ru/film/1423547/',
            },
            {
                id: 208,
                name: 'Старые клыки',
                originalName: 'Old Fangs',
                yearProduction: 2009,
                country: 'Ирландия',
                director: 'Адриен Мериго, Алан Холли',
                scenario: 'Адриен Мериго',
                producer: 'Росс Мюррэй',
                operator: '',
                composer: 'Martine Altenburger',
                artist: 'Йонас Тилль Хоффманн, Алан Холли, Адриен Мериго',
                installation: 'Росс Мюррэй, Алан Слэттери',
                worldPremiere: '1 июля 2009',
                age:'',
                time: '12 мин', 
                description: 'Молодой волк решил посмотреть родные места, и встретиться со свом отцом, с которым он не виделся с самого детства…',
                poster: '/posters/2/208.webp',
                film: 'https://www.youtube.com/watch?v=8YjPar5qQiA',
                kinopoisk: 'https://www.kinopoisk.ru/film/574909/',
            }
        ]
    },
    {
        id: 3,
        name: 'находки 2.0',
        data: '17.03.2024',
        cover1: 1,
        cover2: 2,
        shorts: [
            {
                id: 301,
                name: 'После конца света',
                originalName: "The World's After (El after del mundo)s",
                yearProduction: 2022,
                country: 'Франция',
                director: 'Florentina González',
                scenario: 'Florentina González, Luz Márquez',
                producer: 'Nicolas Schmerkin, Juliane Robert',
                operator: '',
                composer: 'Juana Molina',
                artist: '',
                installation: '',
                worldPremiere: '22 октября 2022',
                age:'',
                time: '11 мин', 
                description: 'После конца света встречаются и завязывают дружбу два призрака: один из них увлечен социальными сетями, другой увлечен морским дном.',
                poster: '/posters/3/301.webp',
                film: 'https://www.youtube.com/watch?v=RRMnwjmSNH0',
                kinopoisk: 'https://www.imdb.com/title/tt23032082/',
            },
            {
                id: 302,
                name: 'Страус сказал мне, что мир фальшив, и я думаю, что верю в это',
                originalName: 'An Ostrich Told Me the World Is Fake and I Think I Believe It',
                yearProduction: 2022,
                country: 'Австралия',
                director: 'Лахлан Пендрагон',
                scenario: 'Лахлан Пендрагон',
                producer: 'Донна Хэмилтон',
                operator: '',
                composer: 'Envato Market',
                artist: '',
                installation: '',
                worldPremiere: '7 июня 2022',
                age:'',
                time: '11 мин', 
                description: 'История офисного сотрудника, которому говорящий страус помогает выявить недостатки в его личной вселенной.',
                poster: '/posters/3/302.webp',
                film: 'https://vk.com/video-55244031_456241121',
                kinopoisk: 'https://www.kinopoisk.ru/film/5248891/'
            },
            {
                id: 303,
                name: 'Из леса',
                originalName: 'Out of a Forest',
                yearProduction: 2010,
                country: 'Дания',
                director: 'Тобиас Гундорфф Бёсен',
                scenario: 'Тобиас Гундорфф Бёсен',
                producer: 'Мишель Нардон, Henrik Malmgren, Катрин Токс',
                operator: '',
                composer: 'Envato Market',
                artist: 'Тобиас Гундорфф Бёсен, Birgit Kousholt',
                installation: 'Тобиас Гундорфф Бёсен',
                worldPremiere: '6 июля 2010',
                age:'',
                time: '6 мин', 
                description: 'Семья кроликов празднует день рождения под большим деревом, не подозревая, что к ним приближается озорной волк.',
                poster: '/posters/3/303.webp',
                film: 'https://www.youtube.com/watch?v=ZSOgl0H5VeM',
                kinopoisk: 'https://www.imdb.com/title/tt1773610/'
            },
            {
                id: 304,
                name: 'Отпрыск',
                originalName: 'Sprössling',
                yearProduction: 2006,
                country: '?',
                director: '?',
                scenario: '?',
                producer: '?',
                operator: '',
                composer: '?',
                artist: '?',
                installation: '?',
                worldPremiere: '?',
                age:'',
                time: '? мин', 
                description: '?',
                poster: '/posters/3/304.webp',
                film: '?',
                kinopoisk: '?'
            },
            {
                id: 305,
                name: 'Судьба',
                originalName: 'Destino',
                yearProduction: 2002,
                country: 'Франция, США',
                director: 'Доминик Монфери',
                scenario: 'Сальвадор Дали, Джон Хенч, Дональд В. Эрнст',
                producer: 'Бэйкер Бладуорф, Дэйв Боссерт, Рой Эдвард Дисней, ...',
                operator: '',
                composer: '-',
                artist: 'Тьерри Форнье',
                installation: 'Джессика Эмбиндер-Рохас',
                worldPremiere: '2 июня 2003',
                age:'',
                time: '7 мин', 
                description: 'Короткометражный сюрреалистический мультфильм, основанный на балладе Армандо Домингеса.',
                poster: '/posters/3/305.webp',
                film: 'https://www.youtube.com/watch?v=y_TlaxmOKqs',
                kinopoisk: 'https://www.kinopoisk.ru/film/46975/'
            },
            {
                id: 306,
                name: 'Возвращение',
                originalName: 'Возвращение (Le retour)',
                yearProduction: 2013,
                country: 'Россия',
                director: 'Наталья Чернышева',
                scenario: '?',
                producer: '?',
                operator: '?',
                composer: '?',
                artist: '?',
                installation: '?',
                worldPremiere: '20 августа 2013',
                age:'',
                time: '1 мин', 
                description: '',
                poster: '/posters/3/306.webp',
                film: 'https://www.youtube.com/watch?v=OnWGXIumMNg',
                kinopoisk: 'https://www.kinopoisk.ru/film/1048012/'
            },
            {
                id: 307,
                name: 'Неловко (Конфуз)',
                originalName: 'Awkward',
                yearProduction: 2020,
                country: 'США',
                director: 'Nata Metlukh',
                scenario: 'Nata Metlukh',
                producer: 'Nata Metlukh',
                operator: 'Nata Metlukh',
                composer: '-',
                artist: 'Nata Metlukh',
                installation: '',
                worldPremiere: '18 марта 2020',
                age:'',
                time: '4 мин', 
                description: 'День, полный социально неловких моментов.',
                poster: '/posters/3/307.webp',
                film: 'https://vk.com/video13715709_456248956',
                kinopoisk: 'https://www.kinopoisk.ru/film/5090977/'
            },
            {
                id: 308,
                name: 'На краю Земли',
                originalName: 'Au bout du monde',
                yearProduction: 1998,
                country: 'Франция',
                director: 'Константин Бронзит',
                scenario: 'Константин Бронзит',
                producer: 'Патрик Эвено, Жак-Реми Жирер',
                operator: 'Патрик Талларон',
                composer: '-',
                artist: '',
                installation: 'Эрве Гишар',
                worldPremiere: '11 ноября 2000',
                age:'',
                time: '8 мин', 
                description: 'История странной пограничной заставы, стоящей на вершине кавказской горы. В этом мультфильме юмористически описана реальная жизнь почти каждого человека - суматоха не по делу, лишние движения, крики.',
                poster: '/posters/3/308.webp',
                film: 'https://www.kinopoisk.ru/film/157299/',
                kinopoisk: 'https://www.kinopoisk.ru/film/157299/'
            },
            {
                id: 309,
                name: 'Электрофорез – зло',
                originalName: '',
                yearProduction: 2021,
                country: 'Россия',
                director: 'Анна Козлова',
                scenario: 'Анна Козлова',
                producer: 'Александра Кутурга',
                operator: 'Евгений Козлов',
                composer: 'Иван Курочкин, Виталий Талызин',
                artist: 'Марго Китара, Маргарита Арт, Артур Хаттапов',
                installation: 'Евгений Козлов',
                worldPremiere: '27 октября 2021',
                age:'',
                time: '4 мин', 
                description: '',
                poster: '/posters/3/309.webp',
                film: 'https://www.youtube.com/watch?v=56W5d4VeUTk',
                kinopoisk: ''
            },
            {
                id: 310,
                name: 'DyE: Fantasy',
                originalName: 'DyE: Fantasy',
                yearProduction: 2011,
                country: 'Франция',
                director: 'Жереми Перен',
                scenario: 'Жереми Перен, Лоран Сарфати',
                producer: '',
                operator: '',
                composer: '',
                artist: '',
                installation: '',
                worldPremiere: '2011',
                age:'18+',
                time: '4 мин', 
                description: 'Группа подростков пробирается в бассейн, чтобы выпить пива и поцеловаться. Внезапно начинают происходить тревожные вещи, и один из них обнаруживает тревожный секрет на дне бассейна.',
                poster: '/posters/3/310.webp',
                film: 'https://vk.com/video8008043_171441110',
                kinopoisk: 'https://www.imdb.com/title/tt8502590/'
            },
            {
                id: 311,
                name: 'Омлет',
                originalName: 'Omelette',
                yearProduction: 2013,
                country: 'США',
                director: 'Мадлен Шарафьян',
                scenario: 'Мадлен Шарафьян',
                producer: 'Мадлен Шарафьян',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '1 мая 2013',
                age:'',
                time: '3 мин', 
                description: 'История про умную собаку, которая помогает приготовить омлет впавшему в депрессию хозяину.',
                poster: '/posters/3/311.webp',
                film: 'https://vk.com/video197121467_456239026',
                kinopoisk: 'https://www.kinopoisk.ru/film/803438/'
            },
        ]
    },
    {
        id: 4,
        name: 'оскароносные. часть 1',
        data: '28.04.2024',
        cover1: 1,
        cover2: 2,
        shorts: [
            {
                id: 401,
                name: 'Цветы и деревья',
                originalName: "Flowers and Trees",
                yearProduction: 1932,
                country: 'США',
                director: 'Берт Джиллетт',
                scenario: '-',
                producer: 'Уолт Дисней',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '30 июля 1932',
                age:'',
                time: '8 мин', 
                description: 'Весенним утром в лесу разыгрывается романтическая история любви дерева-мальчика и дерева-девочки, не обходится без подлого и злого соперника, поющих птичек, танцующих цветочков и всенепременного хеппи-энда.',
                poster: '/posters/4/401.webp',
                film: 'https://www.youtube.com/watch?v=_NKcsg8vE_U',
                kinopoisk: 'https://www.kinopoisk.ru/film/19846/',
            },
            {
                id: 402,
                name: 'Старая мельница',
                originalName: "The Old Mill",
                yearProduction: 1937,
                country: 'США',
                director: 'Уилфред Джексон',
                scenario: 'Дик Рикард',
                producer: 'Уолт Дисней',
                operator: '',
                composer: 'Ли Харлайн',
                artist: '',
                installation: '',
                worldPremiere: '5 ноября 1937',
                age:'',
                time: '9 мин', 
                description: 'Много разной живности поселилось на старой мельнице, стоящей на берегу пруда. Это и мышки, и мудрая сова, и голуби. Днем в пруду плавают утята, а по ночам лягушки устраивают хоровое пение.',
                poster: '/posters/4/402.webp',
                film: 'https://www.youtube.com/watch?v=YF8QjPq9Ff4',
                kinopoisk: 'https://www.kinopoisk.ru/film/19756/',
            },
            {
                id: 403,
                name: 'Лунная птица',
                originalName: "Moonbird",
                yearProduction: 1959,
                country: 'США',
                director: 'Джон Хабли',
                scenario: 'Фэйт Хабли, Джон Хабли',
                producer: 'Джон Хабли, Фэйт Хабли',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '29 января 1959',
                age:'',
                time: '10 мин', 
                description: 'Два брата поздно вечером отправляются на охоту за лунной птицей. Говорят, она обожает шоколадные конфеты и веселые детские песни...',
                poster: '/posters/4/403.webp',
                film: 'https://www.youtube.com/watch?v=mVclzlQ2lwY',
                kinopoisk: 'https://www.kinopoisk.ru/film/257075/',
            },
            {
                id: 404,
                name: 'Суррогат',
                originalName: "Surogat",
                yearProduction: 1961,
                country: 'Югославия',
                director: 'Душан Вукотич',
                scenario: 'Рудольф Сремеч',
                producer: '-',
                operator: 'Жлатко Сачер',
                composer: 'Томислав Симович',
                artist: 'Звонимир Лончарич',
                installation: 'Теа Брансмид',
                worldPremiere: '3 декабря 2010',
                age:'',
                time: '10 мин', 
                description: 'Фильм о мечтах и смысле жизни на примере маленького кусочка жизни рисованных персонажей, о извечном вопросе взаимоотношения полов.',
                poster: '/posters/4/404.webp',
                film: 'https://www.youtube.com/watch?v=u59XkVwL1Sk',
                kinopoisk: 'https://www.kinopoisk.ru/film/111567/',
            },
            {
                id: 405,
                name: 'Критик',
                originalName: "The Critic",
                yearProduction: 1963,
                country: 'США',
                director: 'Эрнест Пинтофф',
                scenario: 'Мэл Брукс',
                producer: 'Эрнест Пинтофф, Арнольд Стоун',
                operator: '',
                composer: '-',
                artist: 'Боб Хит',
                installation: 'Гарри Чанг',
                worldPremiere: '20 мая 1963',
                age:'',
                time: '4 мин', 
                description: 'Фильм представляет собой скопище непонятных фигур, цветовых пятен и линий, сопровождаемых звуками клавесина и комментариями зрителя, который вслух пытался угадать, что же такое ему показывают, а соседи то ли дело на него шикают, потому как он мешает им наслаждаться прекрасным.',
                poster: '/posters/4/405.webp',
                film: 'https://www.youtube.com/watch?v=8U4CGvDJMw4',
                kinopoisk: 'https://www.kinopoisk.ru/film/16743/',
            },
            {
                id: 406,
                name: 'Трещотка',
                originalName: "The Crunch Bird",
                yearProduction: 1971,
                country: 'США',
                director: 'Тед Петок',
                scenario: '-',
                producer: 'Тед Петок',
                operator: '',
                composer: '-',
                artist: '',
                installation: 'Хелен Кэри',
                worldPremiere: '1971',
                age:'',
                time: '2 мин', 
                description: 'Чтобы сделать необычный подарок мужу, дама отправляется в зоомагазин...',
                poster: '/posters/4/406.webp',
                film: 'https://www.youtube.com/watch?v=tlt7wnumTxI',
                kinopoisk: 'https://www.kinopoisk.ru/film/256827/',
            },
            {
                id: 407,
                name: 'Закрыто по понедельникам',
                originalName: "Closed Mondays",
                yearProduction: 1974,
                country: 'США',
                director: 'Боб Гардинер, Уилл Винтон',
                scenario: 'Боб Гардинер',
                producer: 'Боб Гардинер, Уилл Винтон',
                operator: '',
                composer: 'Билли Скрим',
                artist: '',
                installation: '',
                worldPremiere: '31 октября 1974',
                age:'',
                time: '8 мин', 
                description: 'Нетрезвый человек проникает в закрытый выставочный зал, экспонаты которого вдруг начинают оживать…',
                poster: '/posters/4/407.webp',
                film: 'https://www.youtube.com/watch?v=XI9w9yNbrcM',
                kinopoisk: 'https://www.kinopoisk.ru/film/256900/',
            },
            {
                id: 408,
                name: 'Муха',
                originalName: "A légy",
                yearProduction: 1980,
                country: 'Венгрия',
                director: 'Ференц Рофус',
                scenario: 'Ференц Рофус',
                producer: 'Ференц Рофус',
                operator: 'Золтан Бачо',
                composer: '-',
                artist: '',
                installation: 'Янош Ципоуэр',
                worldPremiere: '11 июня 1982',
                age:'',
                time: '3 мин', 
                description: 'Мир глазами мухи, которая залетает в человеческое жилище.',
                poster: '/posters/4/408.webp',
                film: 'https://www.youtube.com/watch?v=Dclvvps5u8Q',
                kinopoisk: 'https://www.kinopoisk.ru/film/256738/',
            },
            {
                id: 409,
                name: 'Шарада',
                originalName: "Charade",
                yearProduction: 1984,
                country: 'Канада',
                director: 'Джон Миннис',
                scenario: 'Джон Миннис',
                producer: 'Майкл Миллс, Джон Миннис',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '10 апреля 1984',
                age:'',
                time: '5 мин', 
                description: 'В мультфильме двое ведущих по очереди загадывают название фильма или книги. Первый изображает очень доходчиво, но туповатые зрители упорно не могут угадать очевидное. Второй изображает не пойми что, но зрители сразу отгадывают. В конце концов, это выводит первого ведущего из себя…',
                poster: '/posters/4/409.webp',
                film: 'https://www.youtube.com/watch?v=-ewycFpTcdE',
                kinopoisk: 'https://www.kinopoisk.ru/film/256778/',
            },
            {
                id: 410,
                name: 'Оловянная игрушка',
                originalName: "Tin Toy",
                yearProduction: 1988,
                country: 'США',
                director: 'Джон Лассетер',
                scenario: 'Джон Лассетер',
                producer: 'Уильям Ривз',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '2 августа 1988',
                age:'',
                time: '5 мин', 
                description: 'Оловянная игрушка пытается не попасть в руки к ребёнку.',
                poster: '/posters/4/410.webp',
                film: 'https://www.youtube.com/watch?v=DWi2WTqD59A',
                kinopoisk: 'https://www.kinopoisk.ru/film/196665/',
            },
            {
                id: 411,
                name: 'Баланс',
                originalName: "Balance",
                yearProduction: 1989,
                country: 'Германия, Германия (ФРГ)',
                director: 'Кристоф Лауэнштайн, Вольфганг Лауэнштайн',
                scenario: 'Кристоф Лауэнштайн, Вольфганг Лауэнштайн',
                producer: '-',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '20 мая 1989',
                age:'',
                time: '7 мин', 
                description: 'Пять человек на подвешенном к пустоте куске плиты. В середине у него центр тяжести. Делает шаг один человек — плита кренится, поэтому вынуждены шагать и другие. Пока царит согласие, всё в порядке. Но что если появится вещь, которая заставит кого-то из них нарушить слаженность ансамбля в угоду своим интересам?',
                poster: '/posters/4/411.webp',
                film: 'https://www.youtube.com/watch?v=PADVHR-_wOs',
                kinopoisk: 'https://www.kinopoisk.ru/film/256605/',
            },
            {
                id: 412,
                name: 'Старик и море',
                originalName: "The Old Man and the Sea",
                yearProduction: 1999,
                country: 'Россия, Канада, Япония',
                director: 'Александр Петров',
                scenario: 'Александр Петров, Эрнест Хемингуэй',
                producer: 'Тацуо Симамура, Паскаль Блэ, Koichi Hirao, ...',
                operator: 'Сергей Решетников',
                composer: 'Дени Л. Шартран, Норман Роже',
                artist: '',
                installation: 'Дэнис Папильон',
                worldPremiere: '30 июня 1999',
                age:'',
                time: '20 мин', 
                description: 'История дружбы между маленьким деревенским мальчишкой и старым рыбаком. Сантьяго, сильный и гордый человек, он не может смириться с неумолимым течением времени, отнимающем физические силы. Уже много недель он возвращается с моря без улова. Наконец он принимает решение - уйти за добычей далеко-далеко в море и без улова не возвращаться. Только так старый рыбак может вернуть себе уверенность и самоуважение. Рано утром он прощается со своим маленьким другом, с родным берегом, который видит, возможно, в последний раз, и растворяется в темноте морских вод. И все же удача приходит к рыбаку. В его снасти попадается гигантская рыба. Двое суток в море продолжается их поединок, но рыба не сдается и тянет Сантьяго все дальше и дальше в море. Но старый рыбак убедил себя в том, что упорство и сила духа - это то, что принесет ему победу…',
                poster: '/posters/4/412.webp',
                film: 'https://www.kinopoisk.ru/film/26270/',
                kinopoisk: 'https://www.kinopoisk.ru/film/26270/',
            },
            {
                id: 413,
                name: 'Песочник',
                originalName: "Piper",
                yearProduction: 2016,
                country: 'США',
                director: 'Алан Барилларо',
                scenario: 'Алан Барилларо',
                producer: 'Марк Сондхаймер, Джон Лассетер, Эндрю Стэнтон',
                operator: 'Эрик Смитт, Derek Williams',
                composer: 'Эдриан Белью',
                artist: 'Джейсон Димер',
                installation: 'Сара К. Реймерс',
                worldPremiere: '16 июня 2016',
                age:'',
                time: '6 мин', 
                description: 'Маленькому птенцу предстоит преодолеть свои страхи, чтобы научиться добывать еду и увидеть красоту окружающего мира.',
                poster: '/posters/4/413.webp',
                film: 'https://www.kinopoisk.ru/film/984759/',
                kinopoisk: 'https://www.kinopoisk.ru/film/984759/',
            },
        ]
    },
    {
        id: 5,
        name: 'оскароносные. часть 2',
        data: '26.05.2024',
        cover1: 1,
        cover2: 2,
        shorts: [
            {
                id: 501,
                name: 'Анна и Бэлла',
                originalName: "Anna & Bella",
                yearProduction: 1984,
                country: 'Нидерланды',
                director: 'Борге Ринг',
                scenario: '-',
                producer: 'Цилиа ван Дайк',
                operator: '',
                composer: '-',
                artist: '',
                installation: 'Ханс Перк',
                worldPremiere: '16 августа 1984',
                age:'',
                time: '8 мин', 
                description: 'Две пожилые сестры проводят чудесный вечер в воспоминаниях молодости - со старым фотоальбомом и изрядным количеством красного вина.',
                poster: '/posters/5/501.webp',
                film: 'https://www.youtube.com/watch?v=2QKgsh7VP3M',
                kinopoisk: 'https://www.kinopoisk.ru/film/250029/',
            },
            {
                id: 502,
                name: 'В мире животных',
                originalName: "Creature Comforts",
                yearProduction: 1989,
                country: 'Великобритания',
                director: 'Ник Парк',
                scenario: 'Ник Парк',
                producer: 'Сара Маллок, Алан Гарднер',
                operator: 'Энди МакКормэк, Фред Рид, Дэйв Алекс Риддетт, ...',
                composer: '-',
                artist: '',
                installation: 'Уильям Энналс',
                worldPremiere: '15 июля 1989',
                age:'',
                time: '5 мин', 
                description: 'Революционное мокьюментари, построенное на настоящих интервью с иммигрантами, которые в мультфильме уподобляются зверям из зоопарка… за счет чего возникает комический и печальный одновременно эффект.',
                poster: '/posters/5/502.webp',
                film: 'https://www.youtube.com/watch?v=PCOWE0EiCyo',
                kinopoisk: 'https://www.kinopoisk.ru/film/22406/',
            },
            {
                id: 503,
                name: 'Харви Крампет',
                originalName: "Harvie Krumpet",
                yearProduction: 2003,
                country: 'Австралия',
                director: 'Адам Бенжамин Эллиот',
                scenario: 'Адам Бенжамин Эллиот',
                producer: 'Мелани Кумбс',
                operator: 'Адам Бенжамин Эллиот',
                composer: '-',
                artist: '',
                installation: 'Билл Мерфи',
                worldPremiere: '19 июня 2003',
                age:'',
                time: '23 мин', 
                description: 'История грустной и странной жизни Харви, родившегося в Европе и после серии неудач переехавшего в Австралию. Единственной постоянной вещью в его жизни остается книжка, куда он записывает все события его жизни.',
                poster: '/posters/5/503.webp',
                film: 'https://www.youtube.com/watch?v=ejsmEhhY-CM',
                kinopoisk: 'https://www.kinopoisk.ru/film/70922/',
            },
            {
                id: 504,
                name: 'Харви Крампет',
                originalName: "Harvie Krumpet",
                yearProduction: 2003,
                country: 'Австралия',
                director: 'Адам Бенжамин Эллиот',
                scenario: 'Адам Бенжамин Эллиот',
                producer: 'Мелани Кумбс',
                operator: 'Адам Бенжамин Эллиот',
                composer: '-',
                artist: '',
                installation: 'Билл Мерфи',
                worldPremiere: '19 июня 2003',
                age:'',
                time: '23 мин', 
                description: 'История грустной и странной жизни Харви, родившегося в Европе и после серии неудач переехавшего в Австралию. Единственной постоянной вещью в его жизни остается книжка, куда он записывает все события его жизни.',
                poster: '/posters/5/504.webp',
                film: 'https://www.youtube.com/watch?v=ejsmEhhY-CM',
                kinopoisk: 'https://www.kinopoisk.ru/film/70922/',
            },
            {
                id: 505,
                name: 'Петя и волк',
                originalName: "Peter & the Wolf",
                yearProduction: 2006,
                country: 'Великобритания, Польша, Норвегия, Мексика',
                director: 'Сьюзи Темплтон',
                scenario: 'Марианела Мальдонадо, Сергей Прокофьев, Сьюзи Темплтон',
                producer: 'Алан Дьюхерст, Хью Уэлшман, Збигнев Змудски, ...',
                operator: 'Хью Гордон, Миколай Ярошевич',
                composer: 'Сергей Прокофьев',
                artist: 'Джейн Мортон, Марек Скробецкий, Войцех Яворский, ...',
                installation: 'Тони Фиш, Сьюзи Темплтон',
                worldPremiere: '23 сентября 2006',
                age:'',
                time: '32 мин', 
                description: 'Мальчик Петя живет вместе с дедушкой в доме за забором на краю леса. Дедушка запрещает Пете выходить из дома, поэтому у него нет друзей среди детей: его друзья - гусь да озорная птица.Но Петю одолевает любопытство, и однажды, несмотря на запрет, он бежит в открытый мир на поиски приключений...',
                poster: '/posters/5/505.webp',
                film: 'https://www.kinopoisk.ru/film/271006/',
                kinopoisk: 'https://www.kinopoisk.ru/film/271006/',
            },
            {
                id: 506,
                name: 'Меню',
                originalName: "Feast",
                yearProduction: 2014,
                country: 'США, Япония',
                director: 'Патрик Осборн',
                scenario: 'Патрик Осборн, Николь Митчелл, Рэймонд С. Перси',
                producer: 'Кристина Рид, Рой Конли, Джон Лассетер',
                operator: '',
                composer: 'Алекс Эберт',
                artist: 'Джефф Терли',
                installation: 'Джефф Дрэхейм',
                worldPremiere: '10 июня 2014',
                age:'',
                time: '6 мин', 
                description: 'История любви из жизни одного человека глазами его лучшего друга, собаки по имени Винстон, показанная через еду, которую они делят.',
                poster: '/posters/5/506.webp',
                film: 'https://www.kinopoisk.ru/film/842712/',
                kinopoisk: 'https://www.kinopoisk.ru/film/842712/',
            },
            {
                id: 507,
                name: 'Дом из маленьких кубиков',
                originalName: "Tsumiki no ie",
                yearProduction: 2008,
                country: 'Япония',
                director: 'Кунио Като',
                scenario: 'Кэнъя Хирата',
                producer: 'Масанори Кусакабэ, Юко Син',
                operator: 'Кунио Като',
                composer: 'Кэндзи Кондо',
                artist: 'Кунио Като',
                installation: 'Хироми Исибаси, Кунио Като',
                worldPremiere: '10 июня 2008',
                age:'',
                time: '12 мин', 
                description: 'Одинокий старик живёт в доме, который уходит корнями в глубину из-за постоянно поднимающего уровня воды, поэтому он вынужден строить этаж за этажом. Так и живёт. Однажды, во время очередной достройки своего импровизированного небоскреба, он нечаянно роняет свою любимую трубку.',
                poster: '/posters/5/507.webp',
                film: 'https://www.kinopoisk.ru/film/439755/',
                kinopoisk: 'https://www.kinopoisk.ru/film/439755/',
            },
            {
                id: 508,
                name: 'Господин Иллюминатор',
                originalName: "Mr Hublot",
                yearProduction: 2013,
                country: 'Люксембург, Франция',
                director: 'Лорен Уитц, Александр Эспигарес',
                scenario: 'Лорен Уитц',
                producer: 'Лорен Уитц',
                operator: 'Лорен Уитц',
                composer: 'Франсуа Русселот',
                artist: 'Паскаль Тьебо',
                installation: '',
                worldPremiere: '20 июня 2013',
                age:'',
                time: '11 мин', 
                description: 'Главный герой живет в абсурдном, постиндустриальном мире, где исчезла природа и большинство «человеческих» отношений.',
                poster: '/posters/5/508.webp',
                film: 'https://www.kinopoisk.ru/film/806273/',
                kinopoisk: 'https://www.kinopoisk.ru/film/806273/',
            },
            {
                id: 509,
                name: 'Война окончена! Вдохновлено музыкой Джона и Йоко',
                originalName: 'War Is Over!',
                yearProduction: 2023,
                country: 'США',
                director: 'Дэйв Маллинз',
                scenario: 'Дэйв Маллинз, Шон Леннон',
                producer: 'Sophie Cherry, Брэд Букер, Дэвид Конли, ...',
                operator: 'Антонио Риестра, Дэвид Скотт',
                composer: 'Томас Ньюман',
                artist: 'Zac Retz',
                installation: 'Джон К. Карр',
                worldPremiere: '21 сентября 2023',
                age:'',
                time: '11 мин', 
                description: '',
                poster: '/posters/5/509.webp',
                film: 'https://www.kinopoisk.ru/film/5445934/',
                kinopoisk: 'https://www.kinopoisk.ru/film/5445934/'
            },
        ]
    },
    {
        id: 6,
        name: 'советское нечто',
        data: '16.06.2024',
        cover1: 1,
        cover2: 2,
        shorts: [
            {
                id: 601,
                name: 'Ёжик в тумане',
                originalName: "",
                yearProduction: 1975,
                country: 'СССР',
                director: 'Юрий Норштейн',
                scenario: 'Сергей Козлов',
                filmDirector: '-',
                producer: '',
                operator: 'Александр Жуковский',
                composer: 'Михаил Меерович',
                artist: 'Франческа Ярбусова',
                installation: 'Надежда Трещёва',
                worldPremiere: '23 октября 1975',
                age:'',
                time: '10 мин', 
                description: 'По вечерам Ёжик ходил к Медвежонку в гости считать звёзды. Они усаживались на брёвнышке и, прихлёбывая чай, смотрели на звёздное небо. Оно висело над крышей, прямо за печной трубой. Справа от трубы были звёзды Медвежонка, а слева — Ёжика.',
                poster: '/posters/6/601.webp',
                film: 'https://www.kinopoisk.ru/film/42461/',
                kinopoisk: 'https://www.kinopoisk.ru/film/42461/',
            },
            {
                id: 602,
                name: 'Мелочи жизни',
                originalName: "",
                yearProduction: 1977,
                country: 'СССР',
                director: 'Валентин Караваев',
                scenario: 'Галина Караваева, Валентин Караваев',
                filmDirector: 'Любовь Бутырина',
                producer: '',
                operator: 'Михаил Друян',
                composer: 'Игорь Якушенко',
                artist: 'Галина Караваева, Валентин Караваев',
                installation: 'Галина Смирнова',
                worldPremiere: '1977',
                age:'',
                time: '8 мин', 
                description: 'Две миниатюры, высмеивающие пьяниц и тех, кто им помогает.',
                poster: '/posters/6/602.webp',
                film: 'https://www.kinopoisk.ru/film/627325/',
                kinopoisk: 'https://www.kinopoisk.ru/film/627325/',
            },
            {
                id: 603,
                name: 'Его жена курица',
                originalName: "",
                yearProduction: 1990,
                country: 'СССР',
                director: 'Игорь Ковалёв',
                scenario: 'Игорь Ковалёв, Евгений Назаренко',
                filmDirector: '-',
                producer: '',
                operator: 'Иосиф Голомб',
                composer: 'Александр Гольдштейн',
                artist: 'Игорь Ковалёв',
                installation: '',
                worldPremiere: '29 января 2019',
                age:'',
                time: '12 мин', 
                description: 'Иллюстрация традиционного образа семейной жизни. Про то, что иногда лучше не знать правду.',
                poster: '/posters/6/603.webp',
                film: 'https://www.youtube.com/watch?v=ymWkKaDQkwQ',
                kinopoisk: 'https://www.kinopoisk.ru/film/42429/',
            },
            {
                id: 604,
                name: 'В синем море, в белой пене...',
                originalName: "",
                yearProduction: 1984,
                country: 'СССР',
                director: 'Роберт Саакянц',
                scenario: 'Роберт Саакянц',
                filmDirector: 'С. Петросян',
                producer: '',
                operator: 'Алиса Кюрдиан',
                composer: 'Роберт Амирханян',
                artist: 'Роберт Саакянц',
                installation: '',
                worldPremiere: '1984',
                age:'',
                time: '8 мин', 
                description: 'Мальчик и дедушка поймали в рыбные сети кувшин. Открыв его, они освободили Владыку моря.',
                poster: '/posters/6/604.webp',
                film: 'https://www.kinopoisk.ru/film/257819/',
                kinopoisk: 'https://www.kinopoisk.ru/film/257819/',
            },
            {
                id: 605,
                name: 'Выкрутасы',
                originalName: "",
                yearProduction: 1987,
                country: 'СССР',
                director: 'Гарри Бардин',
                scenario: 'Гарри Бардин',
                filmDirector: 'Григорий Хмара',
                producer: '',
                operator: 'Владимир Сидоров, Игорь Скидан-Босин',
                composer: '-',
                artist: 'Ирина Ленникова, Ирина Собинова-Кассиль',
                installation: 'Галина Филатова',
                worldPremiere: '28 февраля 1996',
                age:'',
                time: '10 мин', 
                description: 'История проволочного человека, который защиту себя от окружающих довел до абсурда, переделав жену, собаку в колючую проволоку, и отгородил себя от окружающего мира.',
                poster: '/posters/6/605.webp',
                film: 'https://www.kinopoisk.ru/film/45573/',
                kinopoisk: 'https://www.kinopoisk.ru/film/45573/',
            },
            {
                id: 606,
                name: 'Контакт',
                originalName: "",
                yearProduction: 1978,
                country: 'СССР',
                director: 'Владимир Тарасов',
                scenario: 'Александр Костинский',
                filmDirector: 'Любовь Бутырина',
                producer: '',
                operator: 'Кабул Расулов',
                composer: 'Джордж Гершвин, Нино Рота',
                artist: 'Николай Кошкин',
                installation: 'Маргарита Михеева',
                worldPremiere: '1978',
                age:'',
                time: '10 мин', 
                description: 'История о встрече человека и инопланетянина, который пытается изучить Землю посредством имитации увиденного.',
                poster: '/posters/6/606.webp',
                film: 'https://www.kinopoisk.ru/film/261598/',
                kinopoisk: 'https://www.kinopoisk.ru/film/261598/',
            },
            {
                id: 607,
                name: 'Новые большие неприятности',
                originalName: "",
                yearProduction: 1973,
                country: 'СССР',
                director: 'Валентина Брумберг, Зинаида Брумберг',
                scenario: 'Морис Слободской, Яков Костюковский',
                filmDirector: 'Федор Иванов',
                producer: '',
                operator: 'Борис Котов',
                composer: 'Юрий Саульский',
                artist: 'Лана Азарх, Валентин Лалаянц',
                installation: '',
                worldPremiere: '1973',
                age:'',
                time: '10 мин', 
                description: 'Продолжение истории о больших неприятностях взрослых глазами детей.',
                poster: '/posters/6/607.webp',
                film: 'https://www.kinopoisk.ru/film/259930/',
                kinopoisk: 'https://www.kinopoisk.ru/film/259930/',
            },
            {
                id: 608,
                name: 'Остров',
                originalName: "",
                yearProduction: 1973,
                country: 'СССР',
                director: 'Фёдор Хитрук',
                scenario: 'Фёдор Хитрук',
                filmDirector: 'Любовь Бутырина',
                producer: '',
                operator: 'Михаил Друян',
                composer: 'Шандор Каллош',
                artist: 'Эдуард Назаров, Владимир Зуйков',
                installation: 'Изабелла Герасимова',
                worldPremiere: '1973',
                age:'',
                time: '9 мин', 
                description: 'История человека, попавшего на необитаемый остров.',
                poster: '/posters/6/608.webp',
                film: 'https://www.youtube.com/watch?v=K4Z5-3Uful0',
                kinopoisk: 'https://www.kinopoisk.ru/film/42822/',
            },
        ]
    },
    {
        id: 7,
        name: 'советское нечто 2. глубокое погружение',
        data: '14.07.2024',
        cover1: 1,
        cover2: 2,
        shorts: [
            {
                id: 701,
                name: 'Мартынко',
                originalName: "",
                yearProduction: 1987,
                country: 'СССР',
                director: 'Эдуард Назаров',
                scenario: 'Эдуард Назаров, Борис Шергин',
                filmDirector: 'Р. Соколова',
                producer: '',
                operator: 'Михаил Друян',
                composer: '-',
                artist: 'Виктор Чугуевский',
                installation: 'Наталия Степанцева',
                worldPremiere: '5 декабря 2000',
                age:'',
                time: '10 мин', 
                description: 'Мартынко находясь на гауптвахте нашёл колоду волшебных карт, с помощью которой смог запросто обыграть любого! Он сделал быструю карьеру до таможенного министра, обирающего всех иностранцев до нитки прямо при пересечении границы. Однако неразделённые чувства принцессы привели к тому, что его карьере пришёл конец, а его бросили в лесу. Наевшись чудесных яблок, он разрабатывает план мести.',
                poster: '/posters/7/701.webp',
                film: 'https://www.kinopoisk.ru/film/417827/',
                kinopoisk: 'https://www.kinopoisk.ru/film/417827/',
            },
            {
                id: 702,
                name: 'Медвежуть',
                originalName: "",
                yearProduction: 1988,
                country: 'СССР',
                director: 'Василий Кафанов, Алексей Шелманов, Алексей Туркус',
                scenario: 'Василий Кафанов, Алексей Туркус, Алексей Шелманов',
                filmDirector: 'О. Хрулева',
                producer: '',
                operator: 'Александр Чеховский',
                composer: '-',
                artist: 'Елена Боголюбова, Ольга Боголюбова',
                installation: 'Н. Снесарева',
                worldPremiere: '1988',
                age:'',
                time: '10 мин', 
                description: 'О кошмарных сновидениях медведя.',
                poster: '/posters/7/702.webp',
                film: 'https://www.kinopoisk.ru/film/420161/',
                kinopoisk: 'https://www.kinopoisk.ru/film/420161/',
            },
            {
                id: 703,
                name: 'Лев и 9 гиен',
                originalName: "",
                yearProduction: 1988,
                country: 'СССР',
                director: 'Галина Баринова',
                scenario: 'Алексей Студзинский, Виктор Важдаев',
                filmDirector: 'Любовь Бутырина',
                producer: '',
                operator: 'Михаил Друян',
                composer: '-',
                artist: 'Анатолий Петров',
                installation: 'Ольга Василенко',
                worldPremiere: '1988',
                age:'',
                time: '10 мин', 
                description: 'По мотивам африканской народной сказки в пересказе В.Важдаева.',
                poster: '/posters/7/703.webp',
                film: 'https://www.kinopoisk.ru/film/462758/',
                kinopoisk: 'https://www.kinopoisk.ru/film/462758/',
            },
            {
                id: 704,
                name: 'Жар-птица',
                originalName: "",
                yearProduction: 1974,
                country: 'СССР',
                director: 'Рейн Раамат',
                scenario: 'Рейн Раамат, Пауль-Эрик Руммо',
                filmDirector: '-',
                producer: '',
                operator: 'Арви Ильвес',
                composer: 'Рейн Раннап',
                artist: 'Рейн Райдме, Л. Лапин',
                installation: '',
                worldPremiere: '1974',
                age:'',
                time: '7 мин', 
                description: 'Черная кошка окрасила мир в черный цвет, а Жар-птица вернула земле и людям живые краски.',
                poster: '/posters/7/704.webp',
                film: 'https://www.kinopoisk.ru/film/451158/',
                kinopoisk: 'https://www.kinopoisk.ru/film/451158/',
            },
            {
                id: 705,
                name: 'Клубок',
                originalName: "",
                yearProduction: 1968,
                country: 'СССР',
                director: 'Николай Серебряков',
                scenario: 'Овсей Дриз',
                filmDirector: 'Натан Битман',
                producer: '',
                operator: 'Владимир Саруханов',
                composer: 'Эдуард Артемьев',
                artist: 'Алина Спешнева',
                installation: 'Надежда Трещёва',
                worldPremiere: '1968',
                age:'',
                time: '9 мин', 
                description: 'Получила как-то бедная старушка волшебный клубок - все из него связать можно. Связала себе новую одежду, уютный домик. Но показалось ей мало, все больше и больше вещей тянула Старушка из клубка, а потом захотела связать себе молодое лицо, другую жизнь. Тут и кончилась волшебная сила клубка, покатился он в поле, сматывая нить, распуская неправедное богатство, да и самое Старушку тоже. Погубила бедняжку жадность.',
                poster: '/posters/7/705.webp',
                film: 'https://www.kinopoisk.ru/film/224047/',
                kinopoisk: 'https://www.kinopoisk.ru/film/224047/',
            },
            {
                id: 706,
                name: 'Премудрый пескарь',
                originalName: "",
                yearProduction: 1979,
                country: 'СССР',
                director: 'Валентин Караваев',
                scenario: 'Виктор Мережко, Михаил Салтыков-Щедрин',
                filmDirector: 'Любовь Бутырина',
                producer: '',
                operator: 'Борис Котов',
                composer: 'Владимир Мартынов',
                artist: 'Гелий Аркадьев, Сергей Алимов, Наталия Барковская, ...',
                installation: 'Изабелла Герасимова',
                worldPremiere: '12 сентября 1979',
                age:'',
                time: '9 мин', 
                description: 'Когда-то жил пескарь, который был по характеру страшным трусом и не высовывался из своей норы. Пескарь боялся каждой тени, мелькнувшей рядом, вздрагивал от каждого шороха. Вот так вся жизнь и прошла мимо него – ни детей, ни семью он так и не завел. Только перед самой смертью пескарь задумался о пустоте прожитых лет: никому он не помог, никому не нужен и никто о нем никогда не вспомнит…',
                poster: '/posters/7/706.webp',
                film: 'https://www.kinopoisk.ru/film/451270/',
                kinopoisk: 'https://www.kinopoisk.ru/film/451270/',
            },
            {
                id: 707,
                name: 'Лень',
                originalName: "",
                yearProduction: 1979,
                country: 'СССР',
                director: 'Евгений Сивоконь',
                scenario: 'Александр Каневский',
                filmDirector: 'Иван Мазепа',
                producer: '',
                operator: 'Александр Мухин',
                composer: 'Яков Лапинский',
                artist: 'Валентина Серцова',
                installation: '',
                worldPremiere: '2 декабря 2022',
                age:'',
                time: '6 мин', 
                description: 'Мультфильм о всепоглощающей лени.',
                poster: '/posters/7/707.webp',
                film: 'https://www.kinopoisk.ru/film/565247/',
                kinopoisk: 'https://www.kinopoisk.ru/film/565247/',
            },
            {
                id: 708,
                name: 'Урок',
                originalName: "",
                yearProduction: 1987,
                country: 'СССР',
                director: 'Роберт Саакянц',
                scenario: 'Роберт Саакянц',
                filmDirector: '-',
                producer: '',
                operator: 'Алиса Кюрдиан',
                composer: '-',
                artist: 'Роберт Саакянц',
                installation: 'Грачья Бейлерян',
                worldPremiere: '1987',
                age:'18+',
                time: '17 мин', 
                description: 'Космонавты приземляются на неизвестной планете, населенной невиданными растениями и зверьми. Эта планета преподаст жестокий, но мудрый урок беспечным завоевателям.',
                poster: '/posters/7/708.webp',
                film: 'https://www.kinopoisk.ru/film/469753/',
                kinopoisk: 'https://www.kinopoisk.ru/film/469753/',
            },
        ]
    },
    {
        id: 8,
        name: 'youtube, пока живой',
        data: '11.08.2024',
        cover1: 1,
        cover2: 2,
        shorts: [
            {
                id: 801,
                name: 'Закат',
                originalName: "Sundown",
                yearProduction: 2020,
                country: 'Франция',
                director: 'Juliette Brocal, Camille Letouze, Ana Moniz, ...',
                scenario: '-',
                producer: '-',
                operator: '',
                composer: 'Basile Renard, Теодор Вибер',
                artist: '',
                installation: '',
                worldPremiere: '12 ноября 2020',
                age:'',
                time: '5 мин', 
                description: 'Традиционная танцевальная труппа готовится к открытию фестиваля летнего солнцестояния. Группа должна выйти на сцену через несколько минут, но одного участника не хватает.',
                poster: '/posters/8/801.webp',
                film: 'https://www.youtube.com/watch?v=jKh-DP89FPY',
                kinopoisk: 'https://www.imdb.com/title/tt13447558/',
            },
            {
                id: 802,
                name: 'Когда я заменила Камиллу',
                originalName: "Quand j'ai remplacé Camille",
                yearProduction: 2017,
                country: 'Франция',
                director: 'Remy Clarke, Leïla Courtillon, Nathan Otano',
                scenario: '-',
                producer: 'Vincent Courtade, Геренс Куртин',
                operator: '',
                composer: 'Arthur Dairaine Andrianaivo',
                artist: '',
                installation: '',
                worldPremiere: '15 сентября 2017',
                age:'',
                time: '7 мин', 
                description: 'Молодая женщина изо всех сил пытается сосредоточиться на тренировках, в то время как ее недооценивают сверстники и преследует мысль о погибшей пловчихе.',
                poster: '/posters/8/802.webp',
                film: 'https://www.youtube.com/watch?v=-OZ-b0LYxLs',
                kinopoisk: 'https://www.imdb.com/title/tt7453090/',
            },
            {
                id: 803,
                name: 'Зловещая Аллея 03',
                originalName: "Uncanny Alley 01",
                yearProduction: 2024,
                country: 'США',
                director: 'Rodrigo Goulão de Sousa',
                scenario: '-',
                producer: '-',
                operator: '',
                composer: 'Jérémy Ben Ammar',
                artist: 'Mila Monaghan',
                installation: '',
                worldPremiere: '15 сентября 2017',
                age:'',
                time: '3 мин', 
                description: 'Что-то не так с соседом по комнате',
                poster: '/posters/8/803.webp',
                film: 'https://www.youtube.com/watch?v=9QwyzNRms9Y',
                kinopoisk: '',
            },
            {
                id: 804,
                name: 'За маской мечты',
                originalName: "Behind Dreams Mask",
                yearProduction: 2021,
                country: 'США',
                director: '-',
                scenario: '-',
                producer: '-',
                operator: '',
                composer: 'Alex Walker Smith',
                artist: '-',
                installation: '',
                worldPremiere: '26 декабря 2021',
                age:'',
                time: '6 мин', 
                description: '',
                poster: '/posters/8/804.webp',
                film: 'https://www.youtube.com/watch?v=STMhBkjVBHs',
                kinopoisk: '',
            },
            {
                id: 805,
                name: 'Овощеводство',
                originalName: "Vegeversary",
                yearProduction: 2024,
                country: 'США',
                director: 'Sarah Mae Schmidt',
                scenario: '-',
                producer: '-',
                operator: '',
                composer: 'Jo Skillbard',
                artist: '',
                installation: '',
                worldPremiere: '5 января 2024',
                age:'',
                time: '4 мин', 
                description: 'Друзья кролика устраивают для нее мясную вечеринку в честь ее веганской годовщины, наслаждаясь едой, которую она избегает весь год.',
                poster: '/posters/8/805.webp',
                film: 'https://www.youtube.com/watch?v=STMhBkjVBHs',
                kinopoisk: '',
            },
            {
                id: 806,
                name: 'Счастье',
                originalName: "Happiness",
                yearProduction: 2017,
                country: '-',
                director: 'Стив Каттс',
                scenario: '-',
                producer: '-',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '24 ноября 2017',
                age:'',
                time: '4 мин', 
                description: 'История стремления грызуна к счастью.',
                poster: '/posters/8/806.webp',
                film: 'https://www.youtube.com/watch?v=e9dZQelULDk',
                kinopoisk: 'https://www.kinopoisk.ru/film/1108380/',
            },
            {
                id: 807,
                name: 'Уэйд',
                originalName: "Wade",
                yearProduction: 2022,
                country: '-',
                director: 'Kalp Sanghvi, Upamanyu Bhattacharyya',
                scenario: '-',
                producer: '-',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '28 апреля 2022',
                age:'',
                time: '11 мин', 
                description: 'Семья беженцев из-за изменения климата попала в засаду тигра на затопленных улицах Калькутты.',
                poster: '/posters/8/807.webp',
                film: 'https://www.youtube.com/watch?v=KSKjxrL0MWo',
                kinopoisk: '',
            },
            {
                id: 808,
                name: 'Лучший друг',
                originalName: "Best Friend",
                yearProduction: 2018,
                country: 'Франция',
                director: 'Juliana de Lucca, David Feliu, Varun Nair, ...',
                scenario: '-',
                producer: '-',
                operator: '',
                composer: 'Arthur Dairaine Andrianaivo',
                artist: '',
                installation: '',
                worldPremiere: '8 ноября 2018',
                age:'',
                time: '6 мин', 
                description: 'Ближайшее будущее. Одинокий мужчина пристрастился к продукту под названием «Лучший друг», который предлагает ему идеальных виртуальных друзей.',
                poster: '/posters/8/808.webp',
                film: 'https://www.youtube.com/watch?v=j01Hg4QJ6NE',
                kinopoisk: 'https://www.kinopoisk.ru/film/1355030/',
            },
            {
                id: 809,
                name: 'Кода',
                originalName: "Coda",
                yearProduction: 2018,
                country: 'Ирландия',
                director: 'Алан Холли',
                scenario: 'Алан Холли',
                producer: 'Киаран Дини, Адриен Мериго',
                operator: '',
                composer: 'Shane Holly',
                artist: 'Ronan Mc Meel',
                installation: 'Алан Холли',
                worldPremiere: '13 июля 2013',
                age:'',
                time: '9 мин', 
                description: 'Одинокая душа скитается по городу. В парке она встречает смерть, которая раскроет ей множество тайн.',
                poster: '/posters/8/809.webp',
                film: 'https://www.youtube.com/watch?v=MkA3sLyEWdU',
                kinopoisk: 'https://www.kinopoisk.ru/film/809490/',
            },
        ]
    },
    {
        id: 9,
        name: 'youtube, частично живой',
        data: '22.09.2024',
        cover1: 1,
        cover2: 2,
        shorts: [
            {
                id: 901,
                name: 'Серая гвоздика',
                originalName: "Clavel Gris",
                yearProduction: 2023,
                country: '',
                director: 'Antoine Dahan, Clément Delaby, Rayan Takhedmit',
                scenario: '-',
                producer: 'GOBELINS Paris',
                operator: '',
                composer: 'Alexandre Treill, Gaspard Noack-Wilhelm, Guénolé Loterie',
                artist: '',
                installation: '',
                worldPremiere: '15 июня 2023',
                age:'',
                time: '1 мин', 
                description: 'Мексиканский мальчик узнает об ацтекском мифологическом путешествии души к загробной жизни.',
                poster: '/posters/9/901.webp',
                film: 'https://www.youtube.com/watch?v=Dwc_WERFdX0',
                kinopoisk: '',
            },
            {
                id: 902,
                name: 'Пустое место',
                originalName: 'Negative Space',
                yearProduction: 2017,
                country: 'Франция',
                director: 'Ру Кувахата, Макс Портер',
                scenario: 'Макс Портер, Ру Кувахата, Ron Koertge',
                producer: 'Эдвина Льяр, Нидия Сантьяго, Жан-Луи Пади',
                operator: 'Надин Бусс, Саймон Гесрел',
                composer: 'Брэм Мейндерсма',
                artist: 'Ру Кувахата, Макс Портер',
                installation: 'Макс Портер',
                worldPremiere: '13 июня 2017',
                age:'',
                time: '5 мин', 
                description: 'История отношений между сыном и отцом, который по долгу службы постоянно находился в разъездах. Всё, чему научил отец сына за всю свою жизнь - собирать чемодан.',
                poster: '/posters/9/902.webp',
                video: 'https://www.youtube.com/watch?v=KI2lsdXJQ40',
                kinopoisk: 'https://www.kinopoisk.ru/film/1104341/',
            },
            {
                id: 903,
                name: 'Ужин для избранных',
                originalName: 'Dinner for Few',
                yearProduction: 2014,
                country: 'США, Греция',
                director: 'Атанассиос Вакалис',
                scenario: 'Атанассиос Вакалис',
                producer: 'Айкатерини Стергиопулу, Спиро Таравирас, Атанассиос Вакалис',
                operator: 'Атанассиос Вакалис',
                composer: 'Константинос Кристидес',
                artist: 'Атанассиос Вакалис',
                installation: 'Атанассиос Вакалис',
                worldPremiere: '8 сентября 2014',
                age:'18+',
                time: '10 мин', 
                description: 'Во время ужина система кормит некоторых, которые потребляют все ресурсы, в то время как остальные вынуждены довольствоваться объедками. Неизбежная борьба за эти остатки приводит к катастрофическим переменам. Потомок этих перемен оказывается не символом надежды, а точной копией своих родителей.',
                poster: '/posters/9/903.webp',
                video: 'https://www.youtube.com/watch?v=HTDdIO74BuA',
                kinopoisk: 'https://www.kinopoisk.ru/film/1033642/',
            },
            {
                id: 904,
                name: 'Чашки',
                originalName: 'Teacups',
                yearProduction: 2023,
                country: '',
                director: 'Alec Green, Finbar Watson',
                scenario: 'Alec Green, Finbar Watson',
                producer: 'Max Ohman, Lenard Cassimatis, Geordan Bates Associate Producers: Max King, Alex Mayo',
                operator: '',
                composer: 'Stephen Roach, Luke Skaggs, Alex Francis',
                artist: 'Alan Holly, Muireann Mills, Mikai Geronimo, Josh O’Caoimh, Deither Kirby Jay, Rory Byrne',
                installation: '',
                worldPremiere: '15 ноября 2023',
                age:'',
                time: '8 мин', 
                description: 'На протяжении почти полувека Дон Ричи подходил к людям, размышлявшим о самоубийстве, на краю обрыва недалеко от его дома.',
                poster: '/posters/9/904.webp',
                video: 'https://www.youtube.com/watch?v=WK4RKN9Zy-M',
                kinopoisk: '',
            },
            {
                id: 905,
                name: 'Налларбор',
                originalName: 'Nullarbor',
                yearProduction: 2011,
                country: 'Австралия',
                director: 'Алистер Локхарт, Патрик Сарелл',
                scenario: 'Алистер Локхарт, Патрик Сарелл',
                producer: 'Меррин Дженсен, Катрина Мэтерс, Daryl Munton, ...',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '25 февраля 2011',
                age:'',
                time: '11 мин', 
                description: 'Наглый хулиганистый молодчик и спокойный старичок работяга одновременно путешествуют по австралийской долине Налларбор каждый на своей машине. Во время этого кино-путешествия невольным попутчикам придется не только пообщаться, но и даже близко познакомиться.',
                poster: '/posters/9/905.webp',
                video: 'https://www.youtube.com/watch?v=nfK79Xblpus',
                kinopoisk: 'https://www.kinopoisk.ru/film/634557/',
            },
            {
                id: 906,
                name: 'Джей',
                originalName: 'Jay',
                yearProduction: 2020,
                country: '',
                director: '',
                scenario: '',
                producer: '',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '11 марта 2020',
                age:'',
                time: '4 мин', 
                description: 'Вы собираетесь встретиться с Джеем. И ваша жизнь никогда не будет прежней.',
                poster: '/posters/9/906.webp',
                video: 'https://www.youtube.com/watch?v=-fgbu1PsO9Q',
                kinopoisk: '',
            },
            {
                id: 907,
                name: 'В овечьей шкуре',
                originalName: 'W owczej skórze',
                yearProduction: 2020,
                country: '',
                director: 'Sockatiel',
                scenario: '',
                producer: '',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '3 сентября 2024',
                age:'',
                time: '4 мин', 
                description: 'Глупая анимация о том, как волк подвергается давлению со стороны сверстников.',
                poster: '/posters/9/907.webp',
                video: 'https://www.youtube.com/watch?v=R71p94M-z0Y',
                kinopoisk: '',
            },
        ]
    },
    {
        id: 10,
        name: 'бойся и смотри',
        data: '27.10.2024',
        cover1: 1,
        cover2: 2,
        shorts: [
            {
                id: 1001,
                name: 'Мертвая лошадь',
                originalName: "Dead Horse",
                yearProduction: 2022,
                country: 'США',
                director: 'Руби Тейлор',
                scenario: 'Руби Тейлор',
                producer: '-',
                operator: 'Afonso Silva Santos',
                composer: 'Lilly Sharratt',
                artist: '',
                installation: '',
                worldPremiere: '2 ноября 2022',
                age:'',
                time: '4 мин', 
                description: '',
                poster: '/posters/10/1001.webp',
                film: 'https://www.youtube.com/watch?v=tWO2-RDmpDQ',
                kinopoisk: 'https://www.kinopoisk.ru/film/5226479/',
            },
            {
                id: 1002,
                name: 'Полуночный перекус',
                originalName: "Midnight Snack",
                yearProduction: 2015,
                country: 'США',
                director: 'David Romero',
                scenario: 'Elliot Cowan',
                producer: '-',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '6 ноября 2015',
                age:'',
                time: '5 мин', 
                description: 'Бездомный ищет убежища в заброшенном здании, не подозревая об ужасе, который его ждет.',
                poster: '/posters/10/1002.webp',
                film: 'https://www.youtube.com/watch?v=kIAJJg1BxIo',
                kinopoisk: 'https://www.kinopoisk.ru/film/5890236/',
            },
            {
                id: 1003,
                name: 'Приятная гостиница',
                originalName: "Pleasant Inn",
                yearProduction: 2019,
                country: 'США',
                director: 'David Romero',
                scenario: 'David Romero',
                producer: '-',
                operator: 'David Romero',
                composer: 'Мюу',
                artist: '',
                installation: '',
                worldPremiere: '27 октября 2019',
                age:'',
                time: '7 мин', 
                description: 'Одинокая гостиница становится местом, где нужно выжить, сражаясь с чудовищным гостем.',
                poster: '/posters/10/1003.webp',
                film: 'https://www.youtube.com/watch?v=jv4uiR3Aew8',
                kinopoisk: 'https://www.kinopoisk.ru/film/5890238/',
            },
            {
                id: 1004,
                name: 'Кот с человеческими руками',
                originalName: "The Cat with Hands",
                yearProduction: 2001,
                country: 'Великобритания',
                director: 'Роберт Морган',
                scenario: 'Роберт Морган',
                producer: 'Силви Брингас, Эял Шафир',
                operator: 'Маркус Ватерлоо',
                composer: '-',
                artist: 'Джейсон Гилл',
                installation: 'Тони Фиш',
                worldPremiere: '1 июня 2001',
                age:'',
                time: '4 мин', 
                description: 'Жуткая история-байка о коте, который хотел стать человеком.',
                poster: '/posters/10/1004.webp',
                film: 'https://www.youtube.com/watch?v=n4PR9NZlAB4',
                kinopoisk: 'https://www.kinopoisk.ru/film/109015/',
            },
            {
                id: 1005,
                name: 'Разделение',
                originalName: "The Separation",
                yearProduction: 2003,
                country: 'Великобритания',
                director: 'Роберт Морган',
                scenario: 'Роберт Морган',
                producer: 'Силви Брингас',
                operator: 'Филип Кауэн',
                composer: '-',
                artist: 'Стефан Коллонье',
                installation: 'Николя Шодер',
                worldPremiere: '15 октября 2003',
                age:'',
                time: '9 мин', 
                description: 'Они были рождены братьями-близнецами. Но их разделили. Жизнь превратилась в кошмар. Пытаясь вернуть утраченное счастье братья совершают казалось бы невозможное...',
                poster: '/posters/10/1005.webp',
                film: 'https://www.youtube.com/watch?v=ltIG3v_ySuU',
                kinopoisk: 'https://www.kinopoisk.ru/film/109013/',
            },
            {
                id: 1006,
                name: 'Зловещая Аллея 01',
                originalName: "Uncanny Alley 01",
                yearProduction: 2024,
                country: '',
                director: 'Rodrigo Goulão de Sousa ',
                scenario: '',
                producer: '',
                operator: '',
                composer: 'Jérémy Ben Ammar ',
                artist: 'Mila Monaghan',
                installation: '',
                worldPremiere: '7 июня 2024',
                age:'',
                time: '3 мин', 
                description: 'Женщина отвлеклась во время просмотра фильма.',
                poster: '/posters/10/1006.webp',
                film: 'https://www.youtube.com/watch?v=Sf7oGNb8Hng',
                kinopoisk: 'https://www.imdb.com/title/tt32631631/',
            },
            {
                id: 1007,
                name: 'Зловещая Аллея 02',
                originalName: "Uncanny Alley 02",
                yearProduction: 2024,
                country: '',
                director: 'Rodrigo Goulão de Sousa',
                scenario: '',
                producer: '',
                operator: '',
                composer: 'Jérémy Ben Ammar',
                artist: 'Mila Monaghan',
                installation: '',
                worldPremiere: '14 июня 2024',
                age:'',
                time: '3 мин', 
                description: 'К ночному уборщику приходит странный посетитель.',
                poster: '/posters/10/1007.webp',
                film: 'https://www.youtube.com/watch?v=ziaAixpypAM',
                kinopoisk: '',
            },
            {
                id: 1008,
                name: 'Охотники за привидениями | Melvins Macabre',
                originalName: "GHOST HUNTERS | Melvins Macabre",
                yearProduction: 2024,
                country: 'США',
                director: 'MeatCanyon',
                scenario: '',
                producer: '',
                operator: '',
                composer: '',
                artist: '',
                installation: '',
                worldPremiere: '30 июня 2024',
                age:'',
                time: '15 мин', 
                description: '',
                poster: '/posters/10/1008.webp',
                film: 'https://www.youtube.com/watch?v=p6AEP8jTHEM',
                kinopoisk: 'https://www.imdb.com/title/tt32809073/',
            },
        ]
    },
    {
        id: 11,
        name: 'после долгой ночи всегда наступает рассвет',
        data: '24.11.2024',
        cover1: 1,
        cover2: 2,
        shorts: [
            {
                id: 1101,
                name: 'Вещи, которые лучше не путать',
                originalName: "Things You'd Better Not Mix Up",
                yearProduction: 2010,
                country: 'Нидерланды',
                director: 'Joost Lieuwma',
                scenario: 'Joost Lieuwma',
                producer: 'Jiek Weishut',
                operator: '',
                composer: 'Йоррит Клейнен, Александр Роймерс',
                artist: '',
                installation: 'Joost Lieuwma',
                worldPremiere: '8 сентября 2011',
                age:'',
                time: '3 мин', 
                description: 'Ряд вещей, которые лучше не путать.',
                poster: '/posters/11/1101.webp',
                film: 'https://www.youtube.com/watch?v=tRrK9L8ed9g',
                kinopoisk: 'https://www.kinopoisk.ru/film/636735/',
            },
            {
                id: 1102,
                name: 'Енот и фонарик',
                originalName: "Raccoon and the Light",
                yearProduction: 2018,
                country: 'США',
                director: 'Hanna Kim',
                scenario: '-',
                producer: '-',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '1 июня 2018',
                age:'',
                time: '4 мин', 
                description: 'На протяжении почти четырех минут мультфильма «Енот и фонарик» мы наблюдаем за любопытным существом, играющим с фонариком и исследующим темный лес.',
                poster: '/posters/11/1102.webp',
                film: 'https://vk.com/video-32292170_456248224',
                kinopoisk: 'https://www.kinopoisk.ru/film/1434782/',
            },
            {
                id: 1103,
                name: 'Мерло',
                originalName: "Merlot",
                yearProduction: 2016,
                country: 'Италия',
                director: 'Marta Gennari, Giulia Martinelli',
                scenario: '-',
                producer: '-',
                operator: '',
                composer: '-',
                artist: '',
                installation: '',
                worldPremiere: '27 августа 2016',
                age:'',
                time: '6 мин', 
                description: 'История про Красную Шапочку развивается совершенно неожиданным путём.',
                poster: '/posters/11/1103.webp',
                film: 'https://vk.com/video618179102_456239370',
                kinopoisk: 'https://www.kinopoisk.ru/film/4664669/',
            },
            {
                id: 1104,
                name: 'Киоск',
                originalName: "The Kiosk",
                yearProduction: 2013,
                country: 'Швейцария',
                director: 'Анет Мелис',
                scenario: 'Анет Мелис',
                producer: 'Саския фон Вираг',
                operator: '',
                composer: 'Ephrem Lüchinger',
                artist: 'Анет Мелис',
                installation: 'Фи Лихти',
                worldPremiere: '22 июня 2013',
                age:'',
                time: '7 мин', 
                description: 'В течение многих лет киоск был маленьким домом для Ольги, просто потому, что её сидячий образ жизни и любовь к сладкому сделали её больше, чем выход. Чтобы отвлечься, она читает журналы о путешествиях и сама мечтает отправиться на курорт. Абсурдный инцидент помогает ей начать своё путешествие.',
                poster: '/posters/11/1104.webp',
                film: 'https://vk.com/video-31920686_456239523',
                kinopoisk: 'https://www.kinopoisk.ru/film/748177/',
            },
            {
                id: 1105,
                name: 'После дождя',
                originalName: "After the rain",
                yearProduction: 2018,
                country: 'Франция',
                director: 'Rebecca Black, Céline Collin, Juan Pablo De La Rosa Zalamea, ...',
                scenario: '-',
                producer: '-',
                operator: '',
                composer: '-',
                artist: 'Анет Мелис',
                installation: '',
                worldPremiere: '18 января 2020',
                age:'',
                time: '9 мин', 
                description: 'В краю зеленых пастбищ вместе со своим хозяином, старым пастухом-оригиналом, живет счастливый пес. Пастух не просто стрижет овец. Он делает из их шерсти облака, чтобы шел дождь, неизменно возобновляя цикл жизни. Но что будет с долиной, когда пастух умрет? Собаке нужно проявить недюжинную изобретательность и настойчивость, чтобы избежать худшего.',
                poster: '/posters/11/1105.webp',
                film: 'https://www.youtube.com/watch?v=qEaoaRpRRzo',
                kinopoisk: 'https://www.kinopoisk.ru/film/1354936/',
            },
            {
                id: 1106,
                name: 'Бюро находок',
                originalName: "Lost & Found",
                yearProduction: 2018,
                country: 'Австралия',
                director: 'Эндрю Голдсмит, Bradley Slabe',
                scenario: 'Bradley Slabe',
                producer: 'Lucy J. Hayes',
                operator: 'Gerald Thompson',
                composer: 'Джонатан Дрейфус, Адриан Сергович',
                artist: 'Ренни Уотсон',
                installation: 'Эндрю Голдсмит',
                worldPremiere: '11 октября 2018',
                age:'',
                time: '8 мин', 
                description: 'Вязаный игрушечный динозавр должен полностью распутаться, чтобы спасти любовь всей своей жизни.',
                poster: '/posters/11/1106.webp',
                film: 'https://www.youtube.com/watch?v=VBps1IvCyj0',
                kinopoisk: 'https://www.kinopoisk.ru/film/1172795/',
            },
            {
                id: 1107,
                name: '14',
                originalName: "14",
                yearProduction: 2015,
                country: 'Франция',
                director: 'Amélie Graffet, Cyril Flous, Charlotte Da-Ros, Roxane Martinez, David Jurine, Juliette Coutellier',
                scenario: '-',
                producer: 'MoPA',
                operator: '',
                composer: 'Alexandre Chaigniau',
                artist: '',
                installation: '',
                worldPremiere: '2015',
                age:'',
                time: '7 мин', 
                description: 'В 1914 году на одном из этапов Тур де Франс чемпион страны лидирует в гонке, но падает на спуске с перевала Коль дю Турмале…',
                poster: '/posters/11/1107.webp',
                film: 'https://www.youtube.com/watch?v=ShlW5K_tb10',
                kinopoisk: '',
            },
            {
                id: 1108,
                name: 'Котбуль',
                originalName: 'Kitbull',
                yearProduction: 2019,
                country: 'США',
                director: 'Росана Салливан',
                scenario: 'Росана Салливан',
                producer: 'Кэтрин Хендриксон, Линдси Коллинз, Дэвид С. Грант',
                operator: 'Арджун Рейхан',
                composer: 'Эндрю Хименез',
                artist: 'Тим Эватт',
                installation: 'Кэти Шефер',
                worldPremiere: '18 февраля 2019',
                age:'',
                time: '9 мин', 
                description: 'Невероятная связь возникает между двумя существами: бездомным котенком и питбулем. Вместе они понимают, что такое дружба.',
                poster: '/posters/11/1108.webp',
                film: 'https://www.youtube.com/embed/AZS5cgybKcI?si=Am1B4hUoEpr-CJZd',
                kinopoisk: 'https://www.kinopoisk.ru/film/1229863/',
            },
            {
                id: 1109,
                name: 'Снежинка',
                originalName: '',
                yearProduction: 2012,
                country: 'Россия',
                director: 'Наталья Чернышева',
                scenario: 'Наталья Чернышева',
                producer: 'Владимир Гассиев, Анна Джиоева',
                operator: '',
                composer: 'Александр Бабин',
                artist: 'Наталья Чернышева',
                installation: '',
                worldPremiere: '30 декабря 2014',
                age:'',
                time: '6 мин', 
                description: 'Африканский мальчик получает в письме от друга бумажную снежинку. Он кладёт её под подушку и засыпает, мечтая когда-нибудь увидеть много таких снежинок. На следующее утро происходит настоящее чудо: его желание сбывается, и в Африке начинает идти настоящий снег.',
                poster: '/posters/11/1109.webp',
                film: 'https://vk.com/video-58237268_171127813',
                kinopoisk: 'https://www.kinopoisk.ru/film/970136/',
            },
        ]
    },
]