export const data = [
    //150
    {
        id: '2016-148',
        name: 'Общая картина',
        originalName: 'The Bigger Picture',
        nominatedYear: 2015,
        isWin: false,
        yearProduction: 2014,
        platform: '',
        country: 'Великобритания',
        genre: '',
        slogan: "",
        director: 'Дэйзи Джейкобс',
        writer: 'Дэйзи Джейкобс, Дженнифер Майка',
        producer: 'Chris Hees',
        operator: 'Макс Уильямс',
        composer: 'Хув Банфорд',
        design: 'Эло Сооде',
        editor: 'Vera Simmonds',
        worldPremiere: '21 мая 2014',
        age:'',
        time: '8 мин', 
        description: 'История о двух братьях, ухаживающих за пожилой немощной матерью. Младший брат безработный и ему достаётся основная масса забот, старший появляется в доме матери лишь эпизодически, но является её любимцем.',
        poster: '/posters/2015/3.webp',
        video: 'https://vkvideo.ru/video140140535_456239586',
        kinopoisk: 'https://www.kinopoisk.ru/film/841435/',
    },
    {
        id: '2016-146',
        name: 'Меню',
        originalName: 'Feast',
        nominatedYear: 2015,
        isWin: true,
        yearProduction: 2014,
        platform: '',
        country: 'США, Япония',
        genre: '',
        slogan: "",
        director: 'Патрик Осборн',
        writer: 'Патрик Осборн, Николь Митчелл, Рэймонд С. Перси',
        producer: 'Кристина Рид, Рой Конли, Джон Лассетер',
        operator: '',
        composer: 'Алекс Эберт',
        design: 'Джефф Терли',
        editor: 'Джефф Дрэхейм',
        worldPremiere: '10 июня 2014',
        age:'',
        time: '6 мин', 
        description: 'История любви из жизни одного человека глазами его лучшего друга, собаки по имени Винстон, показанная через еду, которую они делят.',
        poster: '/posters/2015/1.webp',
        video: 'https://www.kinopoisk.ru/film/842712/',
        kinopoisk: 'https://www.kinopoisk.ru/film/842712/',
    },
    {
        id: '2016-150',
        name: 'Я и мой Мултон',
        originalName: 'Me and My Moulton',
        nominatedYear: 2015,
        isWin: false,
        yearProduction: 2014,
        platform: '',
        country: 'Норвегия, Канада',
        genre: '',
        slogan: "",
        director: 'Торилл Коув',
        writer: 'Торилл Коув',
        producer: 'Марси Пейдж, Лизе Фернли, Майкл Фукусима, ...',
        operator: '',
        composer: 'Кевин Дин',
        design: 'Торилл Коув',
        editor: 'Элисон Барнс',
        worldPremiere: '10 июня 2014',
        age:'',
        time: '14 мин', 
        description: 'История о девочке, которая хочет получить велосипед от своих родителей, но получает нечто совершенно другое…',
        poster: '/posters/2015/5.webp',
        video: 'https://vkvideo.ru/video140140535_456239587',
        kinopoisk: 'https://www.kinopoisk.ru/film/843967/',
    },
    {
        id: '2016-147',
        name: 'Хранитель плотины',
        originalName: 'The Dam Keeper',
        nominatedYear: 2015,
        isWin: false,
        yearProduction: 2014,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Роберт Кондо, Даисукэ Цуцуми',
        writer: 'John Henry Hinkel, Роберт Кондо, Даисукэ Цуцуми',
        producer: 'Меган Бартел, Роберт Кондо, Кэйн Ли, ...',
        operator: '',
        composer: 'Зак Джонстон, Маттео Робертс',
        design: '',
        editor: 'Брэдли Ферниш',
        worldPremiere: '28 июня 2014',
        age:'',
        time: '18 мин', 
        description: '«Хранитель плотины» — оригинальный анимационный короткометражный фильм художников-мультипликаторов Роберта Кондо и Дайса Цуцуми, рассказывающий историю о молодом поросенке, обремененном важной работой, и о встрече с новым одноклассником, которая меняет все...',
        poster: '/posters/2015/2.webp',
        video: 'https://www.kinopoisk.ru/film/811848/',
        kinopoisk: 'https://www.kinopoisk.ru/film/811848/',
    },
    {
        id: '2016-149',
        name: 'Единственная жизнь',
        originalName: 'A Single Life',
        nominatedYear: 2015,
        isWin: false,
        yearProduction: 2014,
        platform: '',
        country: 'Нидерланды',
        genre: '',
        slogan: "",
        director: 'Марике Блау, Йорис Опринс, Йоб Роггевен',
        writer: 'Йоб Роггевен, Йорис Опринс, Марике Блау',
        producer: 'Марике Блау, Йорис Опринс, Йоб Роггевен',
        operator: '',
        composer: 'Хэппи Кэмпер',
        design: '',
        editor: '',
        worldPremiere: '21 октября 2014',
        age:'',
        time: '3 мин', 
        description: 'Когда Пиа прослушивает загадочную виниловую пластинку, она неожиданно узнает, как ей жить дальше.',
        poster: '/posters/2015/4.webp',
        video: 'https://www.youtube.com/embed/pzAZnOyMTI4?si=CJy9OJ8QaA9bETA4',
        kinopoisk: 'https://www.kinopoisk.ru/film/882239/',
    },

    
    {
        id: '2016-141',
        name: 'Медвежья история',
        originalName: 'Historia de un oso',
        nominatedYear: 2016,
        isWin: true,
        yearProduction: 2014,
        platform: '',
        country: 'Чили',
        genre: '',
        slogan: "",
        director: 'Габриель Осорио Варгас',
        writer: 'Даниэль Кастро, Габриель Осорио Варгас',
        producer: 'Патрицио Эскала, Pato Escala Pierart',
        operator: 'Габриель Осорио Варгас',
        composer: 'Dënver',
        design: 'Antonia Herrera Oesterheld, Габриель Осорио Варгас',
        editor: 'Pato Escala Pierart',
        worldPremiere: '8 мая 2014',
        age:'',
        time: '11 мин', 
        description: 'Анимационная история медведя, который, пытаясь избавиться от тоски, рассказывает о своей беспросветной жизни через механическую диораму. Анимационный фильм отражает трагедию семей, разлученных в условиях диктатуры Аугусто Пиночета.',
        poster: '/posters/2016/1.webp',
        video: 'https://www.kinopoisk.ru/film/931150/',
        kinopoisk: 'https://www.kinopoisk.ru/film/931150/',
    },
    {
        id: '2016-142',
        name: 'Мы не можем жить без космоса',
        originalName: '',
        nominatedYear: 2016,
        isWin: false,
        yearProduction: 2014,
        platform: '',
        country: 'Россия',
        genre: '',
        slogan: "",
        director: 'Константин Бронзит',
        writer: 'Константин Бронзит',
        producer: 'Александр Боярский, Сергей Сельянов',
        operator: '',
        composer: 'Валентин Васенков',
        design: 'Роман Соколов',
        editor: '',
        worldPremiere: '21 августа 2014',
        age:'',
        time: '15 мин', 
        description: 'Два друга мечтают о полете в космос и делают все для достижения своей цели.',
        poster: '/posters/2016/2.webp',
        video: 'https://www.kinopoisk.ru/film/841340/',
        kinopoisk: 'https://www.kinopoisk.ru/film/841340/',
    },
    {
        id: '2016-143',
        name: 'Мир будущего',
        originalName: 'World of Tomorrow',
        nominatedYear: 2016,
        isWin: false,
        yearProduction: 2015,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Дон Херцфельд',
        writer: 'Дон Херцфельд',
        producer: 'Дон Херцфельд',
        operator: 'Дон Херцфельд',
        composer: '-',
        design: 'Дон Херцфельд',
        editor: 'Дон Херцфельд',
        worldPremiere: '22 января 2015',
        age:'',
        time: '17 мин', 
        description: 'Бесцельно нажимая на кнопки приборной панели, маленькая Эмили призывает из будущего своего клона в четвертом поколении, которая показывает ей принципы мироустройства. В эпоху небывалого научного прогресса у человечества появились безграничные возможности и тех же размеров чувство одиночества. Эмили, своим детским восприятием, предстоит охватить мир будущего и увидеть гибель остатков убогой человеческой расы.',
        poster: '/posters/2016/3.webp',
        video: 'https://vk.com/video140140535_456239585',
        kinopoisk: 'https://www.kinopoisk.ru/film/868639/',
    },
    {
        id: '2016-144',
        name: 'Санджай и его команда',
        originalName: "Sanjay's Super Team",
        nominatedYear: 2016,
        isWin: false,
        yearProduction: 2015,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Санджай Патель',
        writer: 'Санджай Патель',
        producer: 'Николь Паради Гриндл, Джон Лассетер',
        operator: '',
        composer: 'Майкл Дэнна',
        design: 'Chris Sasaki',
        editor: 'Kevin Rose-Williams',
        worldPremiere: '27 сентября 2015',
        age:'',
        time: '7 мин', 
        description: 'Пока отец скучно медитирует, маленький индийский мальчик воображает, что он попадет в команду супергероев, состоящую из индуистских богов.',
        poster: '/posters/2016/4.webp',
        video: 'https://www.kinopoisk.ru/film/910672/',
        kinopoisk: 'https://www.kinopoisk.ru/film/910672/',
    },
    {
        id: '2016-145',
        name: 'Пролог',
        originalName: "Prologue",
        nominatedYear: 2016,
        isWin: false,
        yearProduction: 2015,
        platform: '',
        country: 'Великобритания',
        genre: '',
        slogan: "",
        director: 'Ричард Уильямс',
        writer: '-',
        producer: 'Имоджен Саттон',
        operator: '',
        composer: '-',
        design: '',
        editor: '',
        worldPremiere: '17 октября 2015',
        age:'',
        time: '6 мин', 
        description: 'Действие происходит за 2400 лет до нашего времени, когда идёт ожесточённая борьба между спартанцами и воинами Афин.',
        poster: '/posters/2016/5.webp',
        video: 'https://www.youtube.com/embed/FsTnUDhONp4?si=6bwnlRh1HweSuIZb',
        kinopoisk: 'https://www.kinopoisk.ru/film/929089/',
    },
    {
        id: '2017-139',
        name: 'Время взаймы',
        originalName: 'Borrowed Time',
        nominatedYear: 2017,
        isWin: false,
        yearProduction: 2015,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Эндрю Коутс, Lou Hamou-Lhadj',
        writer: 'Эндрю Коутс, Lou Hamou-Lhadj, Mark C. Harris, ...',
        producer: 'Аманда Диринг Джонс',
        operator: 'Luke Martorelli',
        composer: 'Густаво Сантаолалья',
        design: 'Эндрю Коутс, Lou Hamou-Lhadj',
        editor: 'Кэти Грейвз',
        worldPremiere: '31 октября 2015',
        age:'',
        time: '7 мин', 
        description: 'История старого шерифа, который возвращается к несчастному случаю, произошедшему с ним в юности и изменившему всю дальнейшую жизнь. Он отправляется на место трагедии, чтобы облегчить свои страдания и ослабить чувство вины.',
        poster: '/posters/2017/4.webp',
        video: 'https://vk.com/video140140535_456239577',
        kinopoisk: 'https://www.kinopoisk.ru/film/924154/',
    },
    {
        id: '2017-137',
        name: 'Слепая Вайша',
        originalName: 'Blind Vaysha',
        nominatedYear: 2017,
        isWin: false,
        yearProduction: 2016,
        platform: '',
        country: 'Канада',
        genre: '',
        slogan: "",
        director: 'Теодор Ушев',
        writer: 'Теодор Ушев, Georgi Gospodinov',
        producer: 'Марк Бертран, Джули Рой',
        operator: '',
        composer: '-',
        design: '',
        editor: '',
        worldPremiere: '15 февраля 2016',
        age:'',
        time: '8 мин', 
        description: 'Притча о девушке, которая родилась с необычной особенностью: её левый глаз видел только прошлое, а правый - только будущее.',
        poster: '/posters/2017/2.webp',
        video: 'https://www.youtube.com/embed/HSfRTmbrkVc?si=Ts3Xk6M68x5s2QGP',
        kinopoisk: 'https://www.kinopoisk.ru/film/988176/',
    },
    {
        id: '2017-138',
        name: 'Пёрл',
        originalName: 'Pearl',
        nominatedYear: 2017,
        isWin: false,
        yearProduction: 2016,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Патрик Осборн',
        writer: '—',
        producer: 'Дэвид Айзенманн, Карен Дюфильо, Реджина Дуган, ...',
        operator: '',
        composer: '-',
        design: 'Туна Бора',
        editor: 'Стивен Райли',
        worldPremiere: '17 апреля 2016',
        age:'',
        time: '6 мин', 
        description: 'Дочь с отцом путешествует по стране в погоне за мечтой.',
        poster: '/posters/2017/3.webp',
        video: 'https://www.youtube.com/embed/tZwAbpbtsb0',
        kinopoisk: 'https://www.kinopoisk.ru/film/976992/',
    },
    {
        id: '2017-136',
        name: 'Песочник',
        originalName: 'Piper',
        nominatedYear: 2017,
        isWin: true,
        yearProduction: 2016,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Алан Барилларо',
        writer: 'Алан Барилларо',
        producer: 'Марк Сондхаймер, Джон Лассетер, Эндрю Стэнтон',
        operator: 'Эрик Смитт, Derek Williams',
        composer: 'Эдриан Белью',
        design: 'Джейсон Димер',
        editor: 'Сара К. Реймерс',
        worldPremiere: '16 июня 2016',
        age:'',
        time: '6 мин', 
        description: 'Маленькому птенцу предстоит преодолеть свои страхи, чтобы научиться добывать еду и увидеть красоту окружающего мира.',
        poster: '/posters/2017/1.webp',
        video: 'https://www.kinopoisk.ru/film/984759/',
        kinopoisk: 'https://www.kinopoisk.ru/film/984759/',
    },
    {
        id: '2017-140',
        name: 'Грушевый сидр и сигареты',
        originalName: 'Pear Cider and Cigarettes',
        nominatedYear: 2017,
        isWin: false,
        yearProduction: 2016,
        platform: '',
        country: 'Канада, Великобритания',
        genre: '',
        slogan: "",
        director: 'Роберт Вэлли',
        writer: 'Роберт Вэлли',
        producer: 'Кара Спеллер, Роберт Трухильо, Роберт Вэлли',
        operator: '',
        composer: '—',
        design: 'Роберт Вэлли',
        editor: 'Роберт Вэлли',
        worldPremiere: '1 июля 2016',
        age:'',
        time: '35 мин', 
        description: 'История взаимоотношений Роберта и его друга детства, который просит вызволить его из военного госпиталя в Китае и помочь добраться до дома в Ванкувере.',
        poster: '/posters/2017/5.webp',
        video: 'https://vk.com/video140140535_456239578',
        kinopoisk: 'https://www.kinopoisk.ru/film/1008876/',
    },
    {
        id: '2018-134',
        name: 'Хулиганские сказки',
        originalName: 'Revolting Rhymes Part One',
        nominatedYear: 2018,
        isWin: false,
        yearProduction: 2016,
        platform: '',
        country: 'Великобритания',
        genre: '',
        slogan: "",
        director: 'Ян Лахойер, Джейкоб Шух, Bin-Han To',
        writer: 'Роальд Даль, Квентин Блейк, Ян Лахойер, ...',
        producer: 'Мартин Поуп, Майкл Роуз, Майк Баклэнд, ...',
        operator: '',
        composer: 'Бен Локет',
        design: 'Надя Мира',
        editor: 'Бенжамин Квобек',
        worldPremiere: '26 декабря 2016',
        age:'',
        time: '29 мин', 
        description: 'Фильм рассказывает, как молодые Белоснежка и Красная Шапочка становятся лучшими подружками. Пока Белоснежка разбирается со злой Королевой, Красная Шапочка вынуждена дома заняться парой голодных волков – один из которых проглотил ее бабушку и надел ее одежду, а другой планирует съесть нескольких наивных поросят.',
        poster: '/posters/2018/4.webp',
        video: 'https://www.kinopoisk.ru/film/1008655/',
        kinopoisk: 'https://www.kinopoisk.ru/film/1008655/',
    },
    {
        id: '2018-132',
        name: 'Вечеринка в саду',
        originalName: 'Garden Party',
        nominatedYear: 2018,
        isWin: false,
        yearProduction: 2017,
        platform: '',
        country: 'Франция',
        genre: '',
        slogan: "",
        director: 'Флориан Бабикян, Венсан Байо, Виктор Кэр, ...',
        writer: '-',
        producer: '-',
        operator: '',
        composer: '',
        design: '',
        editor: '',
        worldPremiere: '28 января 2017',
        age:'',
        time: '7 мин', 
        description: 'На богатой вилле обосновались лягушки, которые уже чувствуют себя хозяевами...',
        poster: '/posters/2018/2.webp',
        video: 'https://www.kinopoisk.ru/film/1088138/',
        kinopoisk: 'https://www.kinopoisk.ru/film/1088138/',
    },
    {
        id: '2018-133',
        name: 'Лу',
        originalName: 'Lou',
        nominatedYear: 2018,
        isWin: false,
        yearProduction: 2016,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Дэйв Маллинз',
        writer: 'Дэйв Маллинз',
        producer: 'Дана Мюррэй, Пит Доктер, Джон Лассетер',
        operator: 'Brian Boyd, Адам Хабиб',
        composer: 'Кристоф Бек',
        design: '',
        editor: 'Энтони Гринберг',
        worldPremiere: '12 марта 2017',
        age:'',
        time: '7 мин', 
        description: 'Хулиган по имени Джей-Джей ведёт себя вызывающе: например, выхватывает у детей игрушки и бросает их. Существо по имени Лу, которое живет в коробке «Потерянное и найденное», преподает хулигану урок в шуточной манере.',
        poster: '/posters/2018/3.webp',
        video: 'https://www.kinopoisk.ru/film/1023437/',
        kinopoisk: 'https://www.kinopoisk.ru/film/1023437/',
    },
    {
        id: '2018-131',
        name: 'Дорогой баскетбол',
        originalName: 'Dear Basketball',
        nominatedYear: 2018,
        isWin: true,
        yearProduction: 2017,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Глен Кин',
        writer: 'Коби Брайант',
        producer: 'Evan Fleischer, Brian Hunt, Дженни Райм, ...',
        operator: '',
        composer: 'Джон Уильямс',
        design: 'Макс Кин',
        editor: '',
        worldPremiere: '23 апреля 2017',
        age:'',
        time: '6 мин', 
        description: 'Рассказ о стихотворении Коби Брайанта «Дорогой баскетбол».',
        poster: '/posters/2018/1.webp',
        video: 'https://www.kinopoisk.ru/film/1049243/',
        kinopoisk: 'https://www.kinopoisk.ru/film/1049243/',
    },
    {
        id: '2018-135',
        name: 'Пустое место',
        originalName: 'Negative Space',
        nominatedYear: 2018,
        isWin: false,
        yearProduction: 2017,
        platform: '',
        country: 'Франция',
        genre: '',
        slogan: "",
        director: 'Ру Кувахата, Макс Портер',
        writer: 'Макс Портер, Ру Кувахата, Ron Koertge',
        producer: 'Эдвина Льяр, Нидия Сантьяго, Жан-Луи Пади',
        operator: 'Надин Бусс, Саймон Гесрел',
        composer: 'Брэм Мейндерсма',
        design: 'Ру Кувахата, Макс Портер',
        editor: 'Макс Портер',
        worldPremiere: '13 июня 2017',
        age:'',
        time: '5 мин', 
        description: 'История отношений между сыном и отцом, который по долгу службы постоянно находился в разъездах. Всё, чему научил отец сына за всю свою жизнь - собирать чемодан.',
        poster: '/posters/2018/5.webp',
        video: 'https://vk.com/video140140535_456239576',
        kinopoisk: 'https://www.kinopoisk.ru/film/1104341/',
    },
    {
        id: '2019-130',
        name: 'После полудня',
        originalName: 'Late Afternoon',
        nominatedYear: 2019,
        isWin: false,
        yearProduction: 2017,
        platform: '',
        country: 'Ирландия',
        genre: '',
        slogan: "",
        director: 'Луиз Багнэлл',
        writer: 'Луиз Багнэлл',
        producer: 'Нурия Гонсалес Бланко',
        operator: '',
        composer: 'Colm Mac Con Iomaire',
        design: '',
        editor: 'Алан Слэттери',
        worldPremiere: '15 июля 2017',
        age:'',
        time: '9 мин', 
        description: 'Фильм о пожилой женщине по имени Эмили, которая предается воспоминаниям за чашкой чая. Заново переживая моменты своего прошлого, Эмили переоценивает свою жизнь благодаря неожиданным открытиям, которые ей удается обнаружить.',
        poster: '/posters/2019/5.webp',
        video: 'https://www.youtube.com/embed/62YX7VQkOdM?si=i-K5fVEQekQLjIWx',
        kinopoisk: 'https://www.kinopoisk.ru/film/1081355/',
    },
    {
        id: '2019-129',
        name: 'Выходные',
        originalName: 'Weekends',
        nominatedYear: 2019,
        isWin: false,
        yearProduction: 2017,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Тревор Хименес',
        writer: 'Тревор Хименес',
        producer: 'Джереми Слоум, Мэтти Брем',
        operator: '',
        composer: 'Эндрю Вернон',
        design: 'Chris Sasaki',
        editor: 'Тревор Хименес',
        worldPremiere: '18 октября 2017',
        age:'',
        time: '15 мин', 
        description: 'После развода родителей мальчик на неделе живёт с матерью, а на выходные едет к отцу. Тревожные видения из снов ребёнка смешиваются с реалиями распавшейся семьи.',
        poster: '/posters/2019/4.webp',
        video: 'https://vk.com/video140140535_456239574',
        kinopoisk: 'https://www.kinopoisk.ru/film/1086271/',
    },
    {
        id: '2019-127',
        name: 'Бао',
        originalName: 'Bao',
        nominatedYear: 2019,
        isWin: true,
        yearProduction: 2018,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Доми Ши',
        writer: 'Доми Ши',
        producer: 'Пит Доктер, Джон Лассетер, Бекки Нейман',
        operator: 'Патрик Лин, Иэн Мегиббен',
        composer: 'Тоби Чу',
        design: 'Рона Лю, Дон Шэнк',
        editor: 'Кэтерин Рингголд',
        worldPremiere: '21 апреля 2018',
        age:'',
        time: '8 мин', 
        description: 'Женщина получает шанс стать матерью, когда один из её пельмешков оживает.',
        poster: '/posters/2019/2.webp',
        video: 'https://www.kinopoisk.ru/film/1115649/',
        kinopoisk: 'https://www.kinopoisk.ru/film/1115649/',
    },
    {
        id: '2019-128',
        name: 'Поведение животных',
        originalName: 'Animal Behaviour',
        nominatedYear: 2019,
        isWin: false,
        yearProduction: 2018,
        platform: '',
        country: 'Канада',
        genre: '',
        slogan: "",
        director: 'Дэвид Файн, Элисон Сноуден',
        writer: 'Элисон Сноуден, Дэвид Файн',
        producer: 'Майкл Фукусима',
        operator: '',
        composer: 'Джудит Грубер-Стицер',
        design: '',
        editor: '',
        worldPremiere: '11 июня 2018',
        age:'',
        time: '14 мин', 
        description: '',
        poster: '/posters/2019/3.webp',
        video: 'https://vk.com/video140140535_456239572',
        kinopoisk: 'https://www.kinopoisk.ru/film/1165322/',
    },
    {
        id: '2019-126',
        name: 'Один маленький шаг',
        originalName: 'One Small Step',
        nominatedYear: 2019,
        isWin: false,
        yearProduction: 2018,
        platform: '',
        country: 'США, Китай',
        genre: '',
        slogan: "",
        director: 'Эндрю Чесворт, Бобби Понтильяс',
        writer: 'Бобби Понтильяс, Трент Корри, Чжан Шаофу, ...',
        producer: 'Чжан Шаофу, Hande Zhang',
        operator: 'Эндрю Чесворт',
        composer: 'Стив Хорнер',
        design: 'Бобби Понтильяс',
        editor: 'Эндрю Чесворт, Чжан Шаофу',
        worldPremiere: '25 июня 2018',
        age:'',
        time: '8 мин', 
        description: 'С самого раннего детства Луна мечтала полететь в космос. Её мечту всегда поддерживал отец, который был простым башмачником. Однажды он умирает.',
        poster: '/posters/2019/1.webp',
        video: 'https://www.kinopoisk.ru/film/1224070/',
        kinopoisk: 'https://www.kinopoisk.ru/film/1224070/',
    },
    {
        id: '2020-124',
        name: 'Котбуль',
        originalName: 'Kitbull',
        nominatedYear: 2020,
        isWin: false,
        yearProduction: 2019,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Росана Салливан',
        writer: 'Росана Салливан',
        producer: 'Кэтрин Хендриксон, Линдси Коллинз, Дэвид С. Грант',
        operator: 'Арджун Рейхан',
        composer: 'Эндрю Хименез',
        design: 'Тим Эватт',
        editor: 'Кэти Шефер',
        worldPremiere: '18 февраля 2019',
        age:'',
        time: '9 мин', 
        description: 'Невероятная связь возникает между двумя существами: бездомным котенком и питбулем. Вместе они понимают, что такое дружба.',
        poster: '/posters/2020/4.webp',
        video: 'https://www.youtube.com/embed/AZS5cgybKcI?si=Am1B4hUoEpr-CJZd',
        kinopoisk: 'https://www.kinopoisk.ru/film/1229863/',
    },
    {
        id: '2020-123',
        name: 'Незабываемо',
        originalName: 'Mémorable',
        nominatedYear: 2020,
        isWin: false,
        yearProduction: 2019,
        platform: '',
        country: 'Франция',
        genre: '',
        slogan: "",
        director: 'Брюно Колле',
        writer: 'Брюно Колле',
        producer: 'Жан-Франсуа Ле Корр',
        operator: 'Фабьен Друэ',
        composer: 'Николас Мартин',
        design: '',
        editor: 'Жан-Мари Ле Рест',
        worldPremiere: '11 июня 2019',
        age:'',
        time: '12 мин', 
        description: 'Стареющий художник и его жена изо всех сил пытаются справиться с его прогрессирующей деменцией.',
        poster: '/posters/2020/3.webp',
        video: 'https://vk.com/video140140535_456239569',
        kinopoisk: 'https://www.kinopoisk.ru/film/1276515/',
    },
    {
        id: '2020-125',
        name: 'Сестра',
        originalName: 'Sister',
        nominatedYear: 2020,
        isWin: false,
        yearProduction: 2018,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Сун Сыцы',
        writer: 'Сун Сыцы',
        producer: 'Сун Сыцы',
        operator: 'Сун Сыцы',
        composer: 'Карен Танака',
        design: 'Сун Сыцы',
        editor: 'Сун Сыцы',
        worldPremiere: '15 июня 2018',
        age:'',
        time: '8 мин', 
        description: 'Мужчина вспоминает о своём детстве, проведённом в Китае 1990-х годов, и о назойливой младшей сестре.',
        poster: '/posters/2020/5.webp',
        video: 'https://www.kinopoisk.ru/film/1194611/',
        kinopoisk: 'https://www.kinopoisk.ru/film/1194611/',
    },
    {
        id: '2020-122',
        name: 'Дочь',
        originalName: 'Dcera',
        nominatedYear: 2020,
        isWin: false,
        yearProduction: 2019,
        platform: '',
        country: 'Чехия',
        genre: '',
        slogan: "",
        director: 'Дарья Кащеева',
        writer: 'Дарья Кащеева',
        producer: 'Ондрей Сейноха, Мартин Вандас',
        operator: 'Дарья Кащеева, Баргав Шридхар',
        composer: 'Петр Врба',
        design: '',
        editor: 'Александр Кащеев',
        worldPremiere: '9 августа 2019',
        age:'',
        time: '15 мин', 
        description: 'Отношения отца и маленькой дочери никак не складываются.',
        poster: '/posters/2020/2.webp',
        video: 'https://vk.com/video140140535_456239570',
        kinopoisk: 'https://www.kinopoisk.ru/film/1338233/',
    },
    {
        id: '2020-121',
        name: 'Любовь к волосам',
        originalName: 'Hair Love',
        nominatedYear: 2020,
        isWin: true,
        yearProduction: 2019,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "",
        director: 'Мэттью Черри, Эверетт Доунинг мл., Брюс В. Смит',
        writer: 'Мэттью Черри',
        producer: 'Мэттью Черри, Стэйси Ньютон, Карл Рид, ...',
        operator: '',
        composer: 'Дэниэл Д. Кроуфорд, Пол Монси',
        design: '',
        editor: 'Ник Манц, Илья Оуэнс, К. Брайс Рэндл',
        worldPremiere: '14 августа 2019',
        age:'',
        time: '7 мин', 
        description: 'Отец пытается первый раз в жизни уложить волосы дочери в красивую прическу.',
        poster: '/posters/2020/1.webp',
        video: 'https://www.youtube.com/embed/kNw8V_Fkw28?si=yBEi1VLUn2_YyCEg',
        kinopoisk: 'https://www.kinopoisk.ru/film/1077993/',
    },
    {
        id: '2021-118',
        name: 'Гений места',
        originalName: 'Genius Loci',
        nominatedYear: 2021,
        isWin: false,
        yearProduction: 2020,
        platform: '',
        country: 'Франция',
        genre: '',
        slogan: '',
        director: 'Адриен Мериго',
        writer: 'Адриен Мериго, Николя Плескоф',
        producer: 'Амори Овиз, Реджинальд де Гийбон, Энгерран Детервиль, ...',
        operator: '',
        composer: 'Тео Мериго, Ле Квон Нинх',
        design: '',
        editor: '',
        worldPremiere: '19 января 2020',
        age:'',
        time: '16 мин', 
        description: 'Однажды ночью Рейн, одинокая девушка, видит среди городского хаоса подвижное единство, которое кажется живым, вроде какого-то проводника.',
        poster: '/posters/2021/3.webp',
        video: 'https://vk.com/video140140535_456239567',
        kinopoisk: 'https://www.kinopoisk.ru/film/1423547/',
    },
    {
        id: '2021-120',
        name: 'Если что-то случится, я люблю вас',
        originalName: 'If Anything Happens I Love You',
        nominatedYear: 2021,
        isWin: true,
        yearProduction: 2020,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "«Grieving parents struggle with the loss of their daughter after a school shooting. An elegy on grief»",
        director: 'Майкл Говье, Уилл МакКормак',
        writer: 'Уилл МакКормак, Майкл Говье',
        producer: 'Джералд Чамалс, Лора Дерн, Марианн Гарджер, ...',
        operator: '',
        composer: 'Линдсэй Маркус',
        design: '',
        editor: 'Питер Эттинджер',
        worldPremiere: '7 марта 2020',
        age:'',
        time: '12 мин', 
        description: 'Единственное, что остается у любящих родителей после трагической потери, – это воспоминания.',
        poster: '/posters/2021/1.webp',
        // video: 'https://vk.com/video140140535_456239565',
        video: 'https://www.kinopoisk.ru/film/1347450/',
        kinopoisk: 'https://www.kinopoisk.ru/film/1347450/',
    },
    {
        id: '2021-116',
        name: 'Люди-да',
        originalName: 'Já-Fólkið',
        nominatedYear: 2021,
        isWin: false,
        yearProduction: 2020,
        platform: '',
        country: 'Исландия',
        genre: '',
        slogan: '',
        director: 'Гизли Дарри Халльдорссон',
        writer: 'Гизли Дарри Халльдорссон',
        producer: 'Арнар Гуннарссон, Гизли Дарри Халльдорссон',
        operator: '',
        composer: '',
        design: '',
        editor: '',
        worldPremiere: '15 июня 2020',
        age:'',
        time: '8 мин', 
        description: 'Могут ли ужиться друг с другом совершенно непохожие люди — те, кто ходят в школу, те, кто ходят на работу, занимаются музыкой и любят тишину?',
        poster: '/posters/2021/5.webp',
        video: 'https://vk.com/video140140535_456239568',
        kinopoisk: 'https://www.kinopoisk.ru/film/1393096/'
    },
    {
        id: '2021-117',
        name: 'Опера',
        originalName: 'Opera',
        nominatedYear: 2021,
        isWin: false,
        yearProduction: 2020,
        platform: '',
        country: 'США, Корея Южная',
        genre: '',
        slogan: '',
        director: 'Эрик О',
        writer: '',
        producer: 'Sara K. Sampson',
        operator: '',
        composer: 'Эндрю Вернон',
        design: 'Qian Celine You',
        editor: '',
        worldPremiere: '23 сентября 2020',
        age:'',
        time: '9 мин', 
        description: 'Наше общество и история, наполненные красотой и абсурдом.',
        poster: '/posters/2021/4.webp',
        video: 'https://vk.com/video140140535_456239564',
        kinopoisk: 'https://www.kinopoisk.ru/film/4393448/',
    },
    {
        id: '2021-119',
        name: 'Нора',
        originalName: 'Burrow',
        nominatedYear: 2021,
        isWin: false,
        yearProduction: 2020,
        platform: '',
        country: 'США',
        genre: '',
        slogan: "«A rabbit attempts to dig a burrow and learns there's no shame in asking for help»",
        director: 'Мадлен Шарафьян',
        writer: 'Мадлен Шарафьян',
        producer: 'Mike Capbarat, Michael Capbarat, Линдси Коллинз, ...',
        operator: 'Эндрю Хименез',
        composer: 'Дэвид Лэлли',
        design: '',
        editor: 'Anna Wolitzky',
        worldPremiere: '25 декабря 2020',
        age:'',
        time: '6 мин', 
        description: 'Кролик пытается построить нору своей мечты, смущаясь каждый раз, когда случайно врывается в дом соседа.',
        poster: '/posters/2021/2.webp',
        // video: 'https://vk.com/video140140535_456239566',
        video: 'https://www.kinopoisk.ru/film/4308670/',
        kinopoisk: 'https://www.kinopoisk.ru/film/4308670/',
    },
    {
        id: '2022-114',
        name: 'Дела искусства',
        originalName: 'Affairs of the Art',
        nominatedYear: 2022,
        isWin: false,
        yearProduction: 2021,
        platform: '',
        country: 'Великобритания, Канада',
        genre: '',
        slogan: '',
        director: 'Джоанна Куинн',
        writer: 'Лес Миллс',
        producer: 'Лес Миллс, Майкл Фукусим',
        operator: '',
        composer: 'Бенжамин Тэлботт',
        design: '',
        editor: 'Mia Rose Goddard',
        worldPremiere: '29 января 2021',
        age:'18+',
        time: '16 мин', 
        description: 'О том, сколько навязчивых идей может поразить одну семью.',
        poster: '/posters/2022/2.webp',
        video: 'https://vk.com/video140140535_456239580',
        // video: 'https://mega.nz/embed/AxBUFQRA#ON93lgwXpkcPYwjDSa0-MbZYfuLUYaRzdI4bzES9t4Q',
        kinopoisk: 'https://www.kinopoisk.ru/film/4853661/'
    },
    {
        id: '2022-113',
        name: 'БоксБалет',
        originalName: '',
        nominatedYear: 2022,
        isWin: false,
        yearProduction: 2019,
        platform: '',
        country: 'Россия',
        genre: '',
        slogan: '',
        director: 'Антон Дьяков',
        writer: 'Антон Дьяков, Андрей Васильев',
        producer: 'Александр Боярский, Сергей Сельянов',
        operator: '',
        composer: '',
        design: '',
        editor: '',
        worldPremiere: '14 июня 2021',
        age:'',
        time: '15 мин', 
        description: 'Контраст между грубым внешним и неочевидным чувственным внутренним, противопоставление формы содержанию, сила воздействия одного на другое и вообще возможность такового влияния: все эти вопросы, безусловно отсылающие нас к одной из важнейших философских проблем - «быть и казаться», являются ключевыми в понимании этой истории.',
        poster: '/posters/2022/3.webp',
        video: 'https://vk.com/video140140535_456239557',
        kinopoisk: 'https://www.kinopoisk.ru/film/1378921/'
    },
    {
        id: '2022-111',
        name: 'Зверь',
        originalName: 'Bestia',
        nominatedYear: 2022,
        isWin: false,
        yearProduction: 2021,
        platform: '',
        country: 'Чили',
        genre: '',
        slogan: '',
        director: 'Уго Коваррубьяс',
        writer: 'Уго Коваррубьяс, Martín Erazo',
        producer: 'Cecilia Toro, Мариана Мендес, Leo Beltrán, ...',
        operator: '',
        composer: 'Анхела Акуна',
        design: 'Cecilia Toro',
        editor: 'Уго Коваррубьяс',
        worldPremiere: '14 июня 2021',
        age: '18+',
        time: '16 мин', 
        description: 'Чили, 1975 год. Ингрид работает в Управление национальной разведки. Ее отношения с собакой, своим телом, страхами и разочарованиями становятся переломными для ее сознания.',
        poster: '/posters/2022/5.webp',
        // video: 'https://youtu.be/1qmI0o9BsZo?si=q0gGEVPMrSrKRv_p',
        video: 'https://vk.com/video140140535_456239552',
        kinopoisk: 'https://www.kinopoisk.ru/film/4640766/'
    },
    {
        id: '2022-115',
        name: 'Стеклоочиститель',
        originalName: 'The Windshield Wiper',
        nominatedYear: 2022,
        isWin: true,
        yearProduction: 2021,
        platform: '',
        country: 'Испания, США',
        genre: '',
        slogan: '',
        director: 'Альберто Мьельго',
        writer: 'Альберто Мьельго',
        producer: 'Мануэль Р. Кристобаль, Jordan Harkins, Альберто Мьельго, ...',
        operator: '',
        composer: '',
        design: '',
        editor: 'Альберто Мьельго',
        worldPremiere: '13 июля 2021',
        age:'18+',
        time: '15 мин', 
        description: 'Сидя в кафе и непрерывно куря, мужчина задается вопросом, что такое любовь.',
        poster: '/posters/2022/1.webp',
        // video: 'https://tapeop.dev/?movie=1346747012',
        // video: 'https://vk.com/video140140535_456239551',
        video: 'https://www.kinopoisk.ru/film/4470495/',
        kinopoisk: 'https://www.kinopoisk.ru/film/4470495/'
    },
    {
        id: '2022-112',
        name: 'Робин',
        originalName: 'Robin Robin',
        nominatedYear: 2022,
        isWin: false,
        yearProduction: 2019,
        platform: 'Netflix',
        country: 'Великобритания, США',
        genre: '',
        slogan: '',
        director: 'Дэн Оджари, Майкл Плиз',
        writer: 'Дэн Оджари, Майкл Плиз, Сэм Моррисон',
        producer: 'Хелен Арго, Ричард Бик, Шон Кларк, ...',
        operator: 'Дэйв Алекс Риддетт',
        composer: 'Бенедикт Плиз, Бет Портер',
        design: 'Matt Forsythe, Ричард Эдмундс, Саймон Фаррелл',
        editor: 'Крис Морелл',
        worldPremiere: '9 октября 2021',
        age:'0+',
        time: '32 мин', 
        description: 'Яйцо, из которого появилась Робин, случайно попало на свалку — так она оказалась в любящей семье мышей. Со временем их различия становятся всё более очевидны. Решив доказать родным, что из неё выйдет отличная мышь, Робин решается на ограбление века.',
        poster: '/posters/2022/4.webp',
        // video: 'https://tapeop.dev/?movie=1640236055',
        // video: 'https://vk.com/video140140535_456239556',
        video: 'https://www.kinopoisk.ru/film/1345142/',
        kinopoisk: 'https://www.kinopoisk.ru/film/1345142/'
    },
    {
        id: '2023-108',
        name: 'Мой год членов',
        originalName: 'My Year of Dicks',
        nominatedYear: 2023,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'США, Исландия',
        genre: '',
        slogan: "",
        director: 'Сара Гуннарсдоуттир',
        writer: 'Памела Рибон',
        producer: 'Сара Гуннарсдоуттир, Жанетт Жаненн, Памела Рибон',
        operator: 'Сара Гуннарсдоуттир',
        composer: 'Адам Блау',
        design: '',
        editor: 'Сара Гуннарсдоуттир',
        worldPremiere: '13 марта 2022',
        age: '18+',
        time: '24 мин', 
        description: 'Техас, 1991 год. 15-летняя Пэм настойчиво пытается лишиться девственности, но её фантазии о первом опыте сексуального контакта не соответствуют суровой реальности. С этого момента Пэм начинает путешествие, посвящённое самопознанию и сексуальному пробуждению, попутно взрослея, набираясь опыта и совершая серию ошибок.',
        poster: '/posters/2023/3.webp',
        // video: 'https://dl1.vibio.tv/4d9452b347c4e4a1a3898671a1aead3d/2953/2953788/output.lq.mp4',
        // video: 'https://vk.com/video140140535_456239563',
        video: 'https://www.kinopoisk.ru/film/5165441/',
        kinopoisk: 'https://www.kinopoisk.ru/film/5165441/'
    },
    {
        id: '2023-106',
        name: 'Продавцы льда',
        originalName: 'Ice Merchants',
        nominatedYear: 2023,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'Португалия, Великобритания, Франция',
        genre: '',
        slogan: '',
        director: 'Жоау Гонсалес',
        writer: 'Жоау Гонсалес',
        producer: 'Бруно Каэтано, Michael Proenca',
        operator: 'Жоау Гонсалес',
        composer: 'Жоау Гонсалес',
        design: 'Жоау Гонсалес',
        editor: 'Жоау Гонсалес',
        worldPremiere: '24 мая 2022',
        age:'',
        time: '14 мин', 
        description: 'Отец и сын живут на вершине скалы. Каждый день они спускаются вниз на парашютах, чтобы продавать лёд в деревушке, расположенной под их скалой.',
        poster: '/posters/2023/5.webp',
        // video: 'https://tapeop.dev/?movie=699455597',
        // video: 'https://vk.com/video140140535_456239558',
        video: 'https://www.kinopoisk.ru/film/5234141/',
        kinopoisk: 'https://www.kinopoisk.ru/film/5234141/'
    },
    {
        id: '2023-109',
        name: 'Страус сказал мне, что мир фальшив, и я думаю, что верю в это',
        originalName: 'An Ostrich Told Me the World Is Fake and I Think I Believe It',
        nominatedYear: 2023,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'Австралия',
        genre: '',
        slogan: '',
        director: 'Лахлан Пендрагон',
        writer: 'Лахлан Пендрагон',
        producer: 'Донна Хэмилтон',
        operator: '',
        composer: 'Envato Market',
        design: '',
        editor: '',
        worldPremiere: '7 июня 2022',
        age:'',
        time: '11 мин', 
        description: 'История офисного сотрудника, которому говорящий страус помогает выявить недостатки в его личной вселенной.',
        poster: '/posters/2023/2.webp',
        // video: 'https://mega.nz/embed/Vl4S2apB#Xz5a1JODS5biuwVWbQJ9dHh-5JeBNgURRJu3h0hSv7s',
        video: 'https://vk.com/video140140535_456239581',
        kinopoisk: 'https://www.kinopoisk.ru/film/5248891/'
    },
    {
        id: '2023-107',
        name: 'Летающий моряк',
        originalName: 'The Flying Sailor',
        nominatedYear: 2023,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'Канада',
        genre: '',
        slogan: '',
        director: 'Аманда Форбис, Венди Тилби',
        writer: 'Аманда Форбис, Венди Тилби',
        producer: 'Дэвид Кристенсен',
        operator: '',
        composer: 'Луиджи Аллемано',
        design: '',
        editor: '',
        worldPremiere: '13 июня 2022',
        age:'',
        time: '8 мин', 
        description: 'Два корабля сталкиваются в гавани, отправляя проходящего мимо моряка ввысь, и он созерцает чудо и хрупкость существования.',
        poster: '/posters/2023/4.webp',
        // video: 'https://vk.com/video140140535_456239559',
        video: 'https://www.kinopoisk.ru/film/5136457/',
        kinopoisk: 'https://www.kinopoisk.ru/film/5136457/'
    },
    {
        id: '2023-110',
        name: 'Мальчик, Крот, Лис и Конь',
        originalName: 'The Boy, the Mole, the Fox and the Horse',
        nominatedYear: 2023,
        isWin: true,
        yearProduction: 2022,
        platform: 'Apple TV+',
        country: 'Великобритания, США',
        genre: '',
        slogan: '',
        director: 'Питер Бэйнтон, Чарли Маккизи',
        writer: 'Джон Крокер, Чарли Маккизи',
        producer: 'Джей Джей Абрамс, Мэттью Фройд, Ханна Мингелла, ...',
        operator: '',
        composer: 'Изобель Уоллер-Бридж',
        design: 'Майк Маккэйн',
        editor: 'Дэниэл Бадин',
        worldPremiere: '23 сентября 2022',
        age:'',
        time: '32 мин', 
        description: 'Гуляя в зимнем лесу, мальчик встречает крота, лиса и коня, с которыми ведёт разговоры о доброте, пирогах, любви к себе и доме. Несмотря на многочисленные различия, компании удаётся найти общий язык и хорошо провести время.',
        poster: '/posters/2023/1.webp',
        // video: 'https://tapeop.dev/?movie=1109537782',
        // video: 'https://vk.com/video130919424_456244545',
        // video: 'https://mega.nz/file/phxmkY4R#2FLlHdZgxz53lE64o9Dn38kkJLx-53dfuDJHM8ZaD-U',
        video: 'https://www.kinopoisk.ru/film/5138530/',
        kinopoisk: 'https://www.kinopoisk.ru/film/5138530/'
    },
    {
        id: '2024-101',
        name: 'Толстокожий',
        originalName: 'Pachyderme',
        nominatedYear: 2024,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'Франция',
        genre: '',
        slogan: '',
        director: 'Stéphanie Clément',
        writer: 'Marc Rius',
        producer: 'Реджинальд де Гийбон, Marc Rius',
        operator: '',
        composer: 'Оливье Милитон',
        design: '',
        editor: '',
        worldPremiere: '24 апреля 2022',
        age:'',
        time: '11 мин', 
        description: 'Как и каждое лето, Луиза остается на несколько дней в деревне у бабушки и дедушки. В разгар этого лета пойдет снег, и толстокожий монстр умрет.',
        poster: '/posters/2024/5.webp',
        // video: 'https://mega.nz/embed/AwAj2DhZ#kwrWDN5jPHx7LccNQfZSwY1bfkdFYHPWixwgVyV6kv8',
        video: 'https://vk.com/video140140535_456239549',
        kinopoisk: 'https://www.kinopoisk.ru/film/5139401/'
    },
    {
        id: '2024-104',
        name: 'Письмо свинье',
        originalName: 'Letter to a Pig',
        nominatedYear: 2024,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'Израиль, Франция',
        genre: '',
        slogan: '',
        director: 'Tal Kantor',
        writer: 'Tal Kantor',
        producer: 'Пьер Боссарон, Эммануэль-Ален Рейналь, Амит Джиселтер',
        operator: 'Arbel Rom',
        composer: 'Пьер Оберкампф',
        design: '',
        editor: 'Efrat Berger',
        worldPremiere: '28 апреля 2022',
        age:'',
        time: '17 мин', 
        description: 'В День памяти переживший Холокост старик перед классом школьников зачитывает письмо, которое он написал свинье, спасшей ему жизнь. После этого одной ученице видится трагическая версия его истории.',
        poster: '/posters/2024/2.webp',
        // video: 'https://mega.nz/embed/J9hgGAib#kWhfuq8JhWyhKCM4uUBkYtBFA4edQI-jOIx6co3DMDs',
        video: 'https://vk.com/video61950003_456248182',
        video: 'https://vk.com/video140140535_456239544',
        kinopoisk: 'https://www.kinopoisk.ru/film/5355992/'
    },
    {
        id: '2024-102',
        name: 'Девяносто пять чувств',
        originalName: 'Ninety-Five Senses',
        nominatedYear: 2024,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'США',
        genre: '',
        slogan: '',
        director: 'Джаред Хесс, Джеруша Хесс',
        writer: 'Крис Боуман, Хаббел Палмер',
        producer: 'Tori Baker, Джастин Лейкоб, Келли Лусли, ...',
        operator: '',
        composer: 'John Hancock',
        design: '',
        editor: '',
        worldPremiere: '13 августа 2022',
        age:'',
        time: '14 мин', 
        description: 'Рассказ о пяти органах чувств человека, у которого осталось не так много времени насладиться ими.',
        poster: '/posters/2024/4.webp',
        // video: 'https://mega.nz/embed/Aw52TI5b#htamumazk4n_1mFZu6LIYVS1bWDUbUvkC3z1HCaH-Wo',
        video: 'https://vk.com/video140140535_456239550',
        kinopoisk: 'https://www.kinopoisk.ru/film/1312813/'
    },
    {
        id: '2024-103',
        name: 'Наша униформа',
        originalName: 'Our Uniform',
        nominatedYear: 2024,
        isWin: false,
        yearProduction: 2023,
        platform: '',
        country: 'Иран',
        genre: '',
        slogan: '',
        director: 'Yegane Moghaddam',
        writer: '',
        producer: 'Jalil Moghaddam',
        operator: '',
        composer: 'Maryanne Tedstone, Michael Tedstone',
        design: '',
        editor: '',
        worldPremiere: '6 мая 2023',
        age:'',
        time: '7 мин', 
        description: 'Иранская девочка раскрывает свои школьные воспоминания, пробираясь через складки и ткани своей старой формы. Она признает, что она всего лишь женщина, и исследует корни этой идеи в школьные годы. Этот фильм — социальная сатира о условностях одежды, навязанных маленьким детям.',
        poster: '/posters/2024/3.webp',
        video: 'https://vk.com/video140140535_456239555',
        kinopoisk: 'https://www.kinopoisk.ru/film/5445935/'
    },
    {
        id: '2024-105',
        name: 'Война окончена! Вдохновлено музыкой Джона и Йоко',
        originalName: 'War Is Over!',
        nominatedYear: 2024,
        isWin: true,
        yearProduction: 2023,
        platform: '',
        country: 'США',
        genre: '',
        slogan: '',
        director: 'Дэйв Маллинз',
        writer: 'Дэйв Маллинз, Шон Леннон',
        producer: 'Sophie Cherry, Брэд Букер, Дэвид Конли, ...',
        operator: 'Антонио Риестра, Дэвид Скотт',
        composer: 'Томас Ньюман',
        design: 'Zac Retz',
        editor: 'Джон К. Карр',
        worldPremiere: '21 сентября 2023',
        age:'',
        time: '11 мин', 
        description: 'На фронте Первой мировой войны почтовый голубь доставляет сообщения с ходами двум солдатам, играющим в шахматы, не подозревая, что они находятся по разные стороны баррикад.',
        poster: '/posters/2024/1.webp',
        // video: 'https://vk.com/video140140535_456239554',
        video: 'https://www.kinopoisk.ru/film/5445934/',
        kinopoisk: 'https://www.kinopoisk.ru/film/5445934/'
    },
];