export const data = [
    // {
    //     name: '',
    //     originalName: '',
    //     nominatedYear: 2021,
    //     isWin: false,
    //     yearProduction: 2019,
    //     platform: '',
    //     country: '',
    //     genre: '',
    //     slogan: '',
    //     director: '',
    //     scenario: '',
    //     producer: '',
    //     operator: '',
    //     composer: '',
    //     artist: '',
    //     installation: '',
    //     worldPremiere: '',
    //     age:'',
    //     time: '', 
    //     description: '',
    //     poster: '',
    //     video: ''
    // },
    // {
    //     name: '',
    //     originalName: '',
    //     nominatedYear: 2021,
    //     isWin: false,
    //     yearProduction: 2019,
    //     platform: '',
    //     country: '',
    //     genre: '',
    //     slogan: '',
    //     director: '',
    //     scenario: '',
    //     producer: '',
    //     operator: '',
    //     composer: '',
    //     artist: '',
    //     installation: '',
    //     worldPremiere: '',
    //     age:'',
    //     time: '', 
    //     description: '',
    //     poster: '',
    //     video: ''
    // },
    {
        id: '2022-01',
        name: 'Стеклоочиститель',
        originalName: 'The Windshield Wiper',
        nominatedYear: 2022,
        isWin: true,
        yearProduction: 2021,
        platform: '',
        country: 'Испания, США',
        genre: '',
        slogan: '',
        director: 'Альберто Мьельго',
        scenario: 'Альберто Мьельго',
        producer: 'Мануэль Р. Кристобаль, Jordan Harkins, Альберто Мьельго, ...',
        operator: '',
        composer: '',
        artist: '',
        installation: 'Альберто Мьельго',
        worldPremiere: '13 июля 2021',
        age:'',
        time: '15 мин', 
        description: 'Сидя в кафе и непрерывно куря, мужчина задается вопросом, что такое любовь.',
        poster: '/posters/2022/1.webp',
        // video: 'https://tapeop.dev/?movie=1346747012',
        video: 'https://vk.com/video140140535_456239551',
        kinopoisk: 'https://www.kinopoisk.ru/film/4470495/'
    },
    {
        id: '2022-02',
        name: 'Дела искусства',
        originalName: 'Affairs of the Art',
        nominatedYear: 2022,
        isWin: false,
        yearProduction: 2021,
        platform: '',
        country: 'Великобритания, Канада',
        genre: '',
        slogan: '',
        director: 'Джоанна Куинн',
        scenario: 'Лес Миллс',
        producer: 'Лес Миллс, Майкл Фукусим',
        operator: '',
        composer: 'Бенжамин Тэлботт',
        artist: '',
        installation: 'Mia Rose Goddard',
        worldPremiere: '29 января 2021',
        age:'',
        time: '16 мин', 
        description: 'О том, сколько навязчивых идей может поразить одну семью.',
        poster: '/posters/2022/2.webp',
        video: 'https://vk.com/video-20905395_456240344',
        // video: 'https://mega.nz/embed/AxBUFQRA#ON93lgwXpkcPYwjDSa0-MbZYfuLUYaRzdI4bzES9t4Q',
        kinopoisk: 'https://www.kinopoisk.ru/film/4853661/'
    },
    {
        id: '2022-03',
        name: 'БоксБалет',
        originalName: 'БоксБалет',
        nominatedYear: 2022,
        isWin: false,
        yearProduction: 2019,
        platform: '',
        country: 'Россия',
        genre: '',
        slogan: '',
        director: 'Антон Дьяков',
        scenario: 'Антон Дьяков, Андрей Васильев',
        producer: 'Александр Боярский, Сергей Сельянов',
        operator: '',
        composer: '',
        artist: '',
        installation: '',
        worldPremiere: '14 июня 2021',
        age:'',
        time: '15 мин', 
        description: 'Контраст между грубым внешним и неочевидным чувственным внутренним, противопоставление формы содержанию, сила воздействия одного на другое и вообще возможность такового влияния: все эти вопросы, безусловно отсылающие нас к одной из важнейших философских проблем - «быть и казаться», являются ключевыми в понимании этой истории.',
        poster: '/posters/2022/3.webp',
        video: 'https://vk.com/video-31920686_456240506',
        kinopoisk: 'https://www.kinopoisk.ru/film/1378921/'
    },
    {
        id: '2022-04',
        name: 'Робин',
        originalName: 'Robin Robin',
        nominatedYear: 2022,
        isWin: false,
        yearProduction: 2019,
        platform: 'Netflix',
        country: 'Великобритания, США',
        genre: '',
        slogan: '',
        director: 'Дэн Оджари, Майкл Плиз',
        scenario: 'Дэн Оджари, Майкл Плиз, Сэм Моррисон',
        producer: 'Хелен Арго, Ричард Бик, Шон Кларк, ...',
        operator: 'Дэйв Алекс Риддетт',
        composer: 'Бенедикт Плиз, Бет Портер',
        artist: 'Matt Forsythe, Ричард Эдмундс, Саймон Фаррелл',
        installation: 'Крис Морелл',
        worldPremiere: '9 октября 2021',
        age:'0+',
        time: '32 мин', 
        description: 'Яйцо, из которого появилась Робин, случайно попало на свалку — так она оказалась в любящей семье мышей. Со временем их различия становятся всё более очевидны. Решив доказать родным, что из неё выйдет отличная мышь, Робин решается на ограбление века.',
        poster: '/posters/2022/4.webp',
        // video: 'https://tapeop.dev/?movie=1640236055',
        video: 'https://vk.com/video140140535_456239556',
        kinopoisk: 'https://www.kinopoisk.ru/film/1345142/'
    },
    {
        id: '2022-05',
        name: 'Зверь',
        originalName: 'Bestia',
        nominatedYear: 2022,
        isWin: false,
        yearProduction: 2021,
        platform: '',
        country: 'Чили',
        genre: '',
        slogan: '',
        director: 'Уго Коваррубьяс',
        scenario: 'Уго Коваррубьяс, Martín Erazo',
        producer: 'Cecilia Toro, Мариана Мендес, Leo Beltrán, ...',
        operator: '',
        composer: 'Анхела Акуна',
        artist: 'Cecilia Toro',
        installation: 'Уго Коваррубьяс',
        worldPremiere: '14 июня 2021',
        age: '18+',
        time: '16 мин', 
        description: 'Чили, 1975 год. Ингрид работает в Управление национальной разведки. Ее отношения с собакой, своим телом, страхами и разочарованиями становятся переломными для ее сознания.',
        poster: '/posters/2022/5.webp',
        // video: 'https://youtu.be/1qmI0o9BsZo?si=q0gGEVPMrSrKRv_p',
        video: 'https://vk.com/video140140535_456239552',
        kinopoisk: 'https://www.kinopoisk.ru/film/4640766/'
    },
    {
        id: '2023-01',
        name: 'Мальчик, Крот, Лис и Конь',
        originalName: 'The Boy, the Mole, the Fox and the Horse',
        nominatedYear: 2023,
        isWin: true,
        yearProduction: 2022,
        platform: 'Apple TV+',
        country: 'Великобритания, США',
        genre: '',
        slogan: '',
        director: 'Питер Бэйнтон, Чарли Маккизи',
        scenario: 'Джон Крокер, Чарли Маккизи',
        producer: 'Джей Джей Абрамс, Мэттью Фройд, Ханна Мингелла, ...',
        operator: '',
        composer: 'Изобель Уоллер-Бридж',
        artist: 'Майк Маккэйн',
        installation: 'Дэниэл Бадин',
        worldPremiere: '23 сентября 2022',
        age:'',
        time: '32 мин', 
        description: 'Гуляя в зимнем лесу, мальчик встречает крота, лиса и коня, с которыми ведёт разговоры о доброте, пирогах, любви к себе и доме. Несмотря на многочисленные различия, компании удаётся найти общий язык и хорошо провести время.',
        poster: '/posters/2023/1.webp',
        // video: 'https://tapeop.dev/?movie=1109537782',
        // video: 'https://vk.com/video130919424_456244545',
        video: 'https://vk.com/video-154816652_456241405',
        kinopoisk: 'https://www.kinopoisk.ru/film/5138530/'
    },
    {
        id: '2023-02',
        name: 'Страус сказал мне, что мир фальшив, и я думаю, что верю в это',
        originalName: 'An Ostrich Told Me the World Is Fake and I Think I Believe It',
        nominatedYear: 2023,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'Австралия',
        genre: '',
        slogan: '',
        director: 'Лахлан Пендрагон',
        scenario: 'Лахлан Пендрагон',
        producer: 'Донна Хэмилтон',
        operator: '',
        composer: 'Envato Market',
        artist: '',
        installation: '',
        worldPremiere: '7 июня 2022',
        age:'',
        time: '11 мин', 
        description: 'История офисного сотрудника, которому говорящий страус помогает выявить недостатки в его личной вселенной.',
        poster: '/posters/2023/2.webp',
        // video: 'https://mega.nz/embed/Vl4S2apB#Xz5a1JODS5biuwVWbQJ9dHh-5JeBNgURRJu3h0hSv7s',
        video: 'https://vk.com/video-55244031_456241121',
        kinopoisk: 'https://www.kinopoisk.ru/film/5248891/'
    },
    {
        id: '2023-03',
        name: 'Мой год членов',
        originalName: 'My Year of Dicks',
        nominatedYear: 2023,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'США, Исландия',
        genre: '',
        slogan: "",
        director: 'Сара Гуннарсдоуттир',
        scenario: 'Памела Рибон',
        producer: 'Сара Гуннарсдоуттир, Жанетт Жаненн, Памела Рибон',
        operator: 'Сара Гуннарсдоуттир',
        composer: 'Адам Блау',
        artist: '',
        installation: 'Сара Гуннарсдоуттир',
        worldPremiere: '13 марта 2022',
        age: '18+',
        time: '24 мин', 
        description: 'Техас, 1991 год. 15-летняя Пэм настойчиво пытается лишиться девственности, но её фантазии о первом опыте сексуального контакта не соответствуют суровой реальности. С этого момента Пэм начинает путешествие, посвящённое самопознанию и сексуальному пробуждению, попутно взрослея, набираясь опыта и совершая серию ошибок.',
        poster: '/posters/2023/3.webp',
        // video: 'https://dl1.vibio.tv/4d9452b347c4e4a1a3898671a1aead3d/2953/2953788/output.lq.mp4',
        video: 'https://vk.com/video-55244031_456240903',
        kinopoisk: 'https://www.kinopoisk.ru/film/5165441/'
    },
    {
        id: '2023-04',
        name: 'Летающий моряк',
        originalName: 'The Flying Sailor',
        nominatedYear: 2023,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'Канада',
        genre: '',
        slogan: '',
        director: 'Аманда Форбис, Венди Тилби',
        scenario: 'Аманда Форбис, Венди Тилби',
        producer: 'Дэвид Кристенсен',
        operator: '',
        composer: 'Луиджи Аллемано',
        artist: '',
        installation: '',
        worldPremiere: '13 июня 2022',
        age:'',
        time: '8 мин', 
        description: 'Два корабля сталкиваются в гавани, отправляя проходящего мимо моряка ввысь, и он созерцает чудо и хрупкость существования.',
        poster: '/posters/2023/4.webp',
        // video: 'https://tapeop.dev/?movie=523564456',
        video: 'https://vk.com/video-31920686_456240619',
        kinopoisk: 'https://www.kinopoisk.ru/film/5136457/'
    },
    {
        id: '2023-05',
        name: 'Продавцы льда',
        originalName: 'Ice Merchants',
        nominatedYear: 2023,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'Португалия, Великобритания, Франция',
        genre: '',
        slogan: '',
        director: 'Жоау Гонсалес',
        scenario: 'Жоау Гонсалес',
        producer: 'Бруно Каэтано, Michael Proenca',
        operator: 'Жоау Гонсалес',
        composer: 'Жоау Гонсалес',
        artist: 'Жоау Гонсалес',
        installation: 'Жоау Гонсалес',
        worldPremiere: '24 мая 2022',
        age:'',
        time: '14 мин', 
        description: 'Отец и сын живут на вершине скалы. Каждый день они спускаются вниз на парашютах, чтобы продавать лёд в деревушке, расположенной под их скалой.',
        poster: '/posters/2023/5.webp',
        // video: 'https://tapeop.dev/?movie=699455597',
        video: 'https://vk.com/video-31920686_456240626',
        kinopoisk: 'https://www.kinopoisk.ru/film/5234141/'
    },
    {
        id: '2024-01',
        name: 'Война окончена! Вдохновлено музыкой Джона и Йоко',
        originalName: 'War Is Over!',
        nominatedYear: 2024,
        isWin: true,
        yearProduction: 2023,
        platform: '',
        country: 'США',
        genre: '',
        slogan: '',
        director: 'Дэйв Маллинз',
        scenario: 'Дэйв Маллинз, Шон Леннон',
        producer: 'Sophie Cherry, Брэд Букер, Дэвид Конли, ...',
        operator: 'Антонио Риестра, Дэвид Скотт',
        composer: 'Томас Ньюман',
        artist: 'Zac Retz',
        installation: 'Джон К. Карр',
        worldPremiere: '21 сентября 2023',
        age:'',
        time: '11 мин', 
        description: '',
        poster: '/posters/2024/1.webp',
        video: 'https://vk.com/video-189089797_456240737',
        kinopoisk: 'https://www.kinopoisk.ru/film/5445934/'
    },
    {
        id: '2024-02',
        name: 'Письмо свинье',
        originalName: 'Letter to a Pig',
        nominatedYear: 2024,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'Израиль, Франция',
        genre: '',
        slogan: '',
        director: 'Tal Kantor',
        scenario: 'Tal Kantor',
        producer: 'Пьер Боссарон, Эммануэль-Ален Рейналь, Амит Джиселтер',
        operator: 'Arbel Rom',
        composer: 'Пьер Оберкампф',
        artist: '',
        installation: 'Efrat Berger',
        worldPremiere: '28 апреля 2022',
        age:'',
        time: '17 мин', 
        description: 'В День памяти переживший Холокост старик перед классом школьников зачитывает письмо, которое он написал свинье, спасшей ему жизнь. После этого одной ученице видится трагическая версия его истории.',
        poster: '/posters/2024/2.webp',
        // video: 'https://mega.nz/embed/J9hgGAib#kWhfuq8JhWyhKCM4uUBkYtBFA4edQI-jOIx6co3DMDs',
        video: 'https://vk.com/video61950003_456248182',
        video: 'https://vk.com/video140140535_456239544',
        kinopoisk: 'https://www.kinopoisk.ru/film/5355992/'
    },
    {
        id: '2024-03',
        name: 'Наша униформа',
        originalName: 'Our Uniform',
        nominatedYear: 2024,
        isWin: false,
        yearProduction: 2023,
        platform: '',
        country: 'Иран',
        genre: '',
        slogan: '',
        director: 'Yegane Moghaddam',
        scenario: '',
        producer: 'Jalil Moghaddam',
        operator: '',
        composer: 'Maryanne Tedstone, Michael Tedstone',
        artist: '',
        installation: '',
        worldPremiere: '6 мая 2023',
        age:'',
        time: '7 мин', 
        description: '',
        poster: '/posters/2024/3.webp',
        video: 'https://vk.com/video140140535_456239555',
        kinopoisk: 'https://www.kinopoisk.ru/film/5445935/'
    },
    {
        id: '2024-04',
        name: 'Девяносто пять чувств',
        originalName: 'Ninety-Five Senses',
        nominatedYear: 2024,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'США',
        genre: '',
        slogan: '',
        director: 'Джаред Хесс, Джеруша Хесс',
        scenario: 'Крис Боуман, Хаббел Палмер',
        producer: 'Tori Baker, Джастин Лейкоб, Келли Лусли, ...',
        operator: '',
        composer: 'John Hancock',
        artist: '',
        installation: '',
        worldPremiere: '13 августа 2022',
        age:'',
        time: '14 мин', 
        description: 'Рассказ о пяти органах чувств человека, у которого осталось не так много времени насладиться ими.',
        poster: '/posters/2024/4.webp',
        // video: 'https://mega.nz/embed/Aw52TI5b#htamumazk4n_1mFZu6LIYVS1bWDUbUvkC3z1HCaH-Wo',
        video: 'https://vk.com/video140140535_456239550',
        kinopoisk: 'https://www.kinopoisk.ru/film/1312813/'
    },
    {
        id: '2024-05',
        name: 'Толстокожий',
        originalName: 'Pachyderme',
        nominatedYear: 2024,
        isWin: false,
        yearProduction: 2022,
        platform: '',
        country: 'Франция',
        genre: '',
        slogan: '',
        director: 'Stéphanie Clément',
        scenario: 'Marc Rius',
        producer: 'Реджинальд де Гийбон, Marc Rius',
        operator: '',
        composer: 'Оливье Милитон',
        artist: '',
        installation: '',
        worldPremiere: '24 апреля 2022',
        age:'',
        time: '11 мин', 
        description: 'Как и каждое лето, Луиза остается на несколько дней в деревне у бабушки и дедушки. В разгар этого лета пойдет снег, и толстокожий монстр умрет.',
        poster: '/posters/2024/5.webp',
        // video: 'https://mega.nz/embed/AwAj2DhZ#kwrWDN5jPHx7LccNQfZSwY1bfkdFYHPWixwgVyV6kv8',
        video: 'https://vk.com/video140140535_456239549',
        kinopoisk: 'https://www.kinopoisk.ru/film/5139401/'
    },
];